SET foreign_key_checks = 0;

TRUNCATE TABLE kalea;
INSERT INTO `kalea` (`id`, `barrutia_id`, `auzoa_id`, `izena`, `google`) VALUES
	(1, NULL, 1, 'Miguel Alduncin (21-45)', 'Calle de Miguel Alduncin'),
	(2, NULL, 8, 'Altxu', 'Paseo de Gaztaño'),
	(121, NULL, 12, 'Txirrita - Maleo', NULL),
	(181, NULL, 18, 'ZZ_Genérico', NULL),
	(1101, NULL, 5, 'Goiko Kalea / C. Arriba', 'Calle de Arriba'),
	(1103, NULL, 5, 'Herriko Plaza', 'Calle de la Magdalena, 1'),
	(1104, NULL, 5, 'Elizako Kalea', 'Calle de la Iglesia'),
	(1105, NULL, 5, 'Madalen Kalea', 'Calle de la Magdalena'),
	(1106, NULL, 5, 'Erdiko Kalea / C. Medio', 'Calle del Medio'),
	(1107, NULL, 5, 'Miguel Alduncin (1-20)', 'Calle de Miguel Alduncin'),
	(1108, NULL, 5, 'Orereta', 'Calle de Orereta'),
	(1109, NULL, 5, 'Pablo Iglesias', 'Avenida de Pablo Iglesias'),
	(1110, NULL, 5, 'Santa Klara', 'Calle de Santa Clara'),
	(1111, NULL, 5, 'Antontxu Sainz Enparantza', NULL),
	(1201, NULL, 5, 'Kapitanenea', 'Calle de Kapitanenea'),
	(1202, NULL, 10, 'Kristobal Gamon', 'Calle de Cristóbal Gamón'),
	(1203, NULL, 5, 'Fernandez de Landa', 'Plaza de Fernández de Landa'),
	(1204, NULL, 5, 'Gamon, Alameda de', 'Alameda de Gamón'),
	(1207, NULL, 10, 'Askatasunaren Martiriak', 'Avenida de los Mártires de la Libertad'),
	(1209, NULL, 5, 'Santxoenea', 'Santxoenea Kalea'),
	(1210, NULL, 5, 'Santa Maria Kalea', 'Calle de Santa María'),
	(1211, NULL, 10, 'Urantzu', 'Uranzu Kalea'),
	(1212, NULL, 5, 'Biteri', 'Calle de Viteri'),
	(1213, NULL, 10, 'Zamalbide', 'Calle de Zamalbide'),
	(1214, NULL, 10, 'Zubiaurre', 'Zubiaurre Kalea'),
	(1301, NULL, 5, 'Foru Plaza', 'Plaza de los Fueros'),
	(1302, NULL, 8, 'Gaztaño', 'Gaztaño Auzoa'),
	(1304, NULL, 5, 'Maria Lezo', 'María Lezo Kalea'),
	(1401, NULL, 6, 'Aizpitarte Pasabidea', 'Pasaje de Aitzbitarte'),
	(1402, NULL, 6, 'Alexander Fleming', 'Alexander Fleming Kalea'),
	(1403, NULL, 6, 'Fanderia Pasealekua', 'Fanderia Etorbidea'),
	(1404, NULL, 6, 'Lartzabal', 'Larzabal'),
	(1406, NULL, 6, 'Salk eta Sabin', 'Salk eta Sabín Kalea'),
	(1407, NULL, 5, 'Tomas Lopez', 'Calle de Tomás López'),
	(1408, NULL, 6, 'Gabierrota Pasealekua', 'Gabierrota Pasealekua'),
	(1501, NULL, 5, 'Beheko Kalea / C. Abajo', 'Calle de Abajo'),
	(1507, NULL, 5, 'Santa Klara Plaza', 'Calle de Santa Clara'),
	(1601, NULL, 5, 'Añarbe', 'Añarbe Kalea'),
	(1602, NULL, 5, 'Bidasoa', 'Bidasoa Kalea'),
	(1603, NULL, 5, 'Lope Isasti', 'Lope de Isasti Kalea'),
	(1604, NULL, 5, 'Kaletxiki', 'Txiki Kalea'),
	(1605, NULL, 5, 'Martin Etxeberria', 'Martín Etxeberria Kalea'),
	(1606, NULL, 5, 'Morronguilleta', 'Calle de Morronguilleta'),
	(1607, NULL, 5, 'Oria', 'Oria Kalea'),
	(1608, NULL, 5, 'Urola Kalea', 'Urola Kalea'),
	(1610, NULL, 5, 'Xenpelar', 'Xenpelar Kalea'),
	(1620, NULL, 5, 'Koldo Mitxelena Plaza', 'Koldo Mitxelena Plaza'),
	(1702, NULL, 7, 'Parke', 'Parkeko Kalea'),
	(1801, NULL, 7, 'Aizkorri Plaza', 'Plaza del Aitzgorri'),
	(1803, NULL, 7, 'Ganbo Plaza', 'Plaza de Ganbo'),
	(1804, NULL, 7, 'Miguel Zabaleta', 'Calle de Miguel Zabaleta'),
	(1805, NULL, 7, 'Urbia Plaza', 'Urbia Plaza'),
	(1806, NULL, 7, 'Yanci', 'Calle Yanci'),
	(1807, NULL, 12, 'Masti Loidi', 'Masti-Loidi Industrialdea'),
	(1901, NULL, 5, 'Alfonso XI.aren Kalea', 'Alfonso XI Kalea'),
	(1903, NULL, 5, 'Francisco Gazkue', 'Francisco Gazkue Kalea'),
	(1904, NULL, 5, 'Jose Erbiti', 'José Erviti Kalea'),
	(1906, NULL, 5, 'Segundo Ispizua', 'Segundo Izpizua Kalea'),
	(1907, NULL, 5, 'Vicente Elicegi', 'Vicente Elizegi Kalea'),
	(2001, NULL, 2, 'Alaberga', 'Irumugarrieta Kalea'),
	(2002, NULL, 5, 'Juan Olazabal', 'Calle de Juan Olazábal'),
	(2103, NULL, 4, 'Kaputxinoa Gaina', 'Capuchinos Puerto'),
	(2201, NULL, 9, 'Donostia - S.Sebastian', 'Donostia-San Sebastián Kalea'),
	(2202, NULL, 9, 'Iztieta Pasealekua', 'Iztieta Pasealekua'),
	(2203, NULL, 9, 'Lezo Pasealekua', 'Lezo Pasealekua'),
	(2205, NULL, 9, 'Pasaia', 'Pasaia Kalea'),
	(2301, NULL, 9, 'Diputazio Plaza', 'Plaza de la Diputación'),
	(2303, NULL, 9, 'Hondarribia', 'Hondarribia Kalea'),
	(2304, NULL, 9, 'Irun', 'Irun Kalea'),
	(2307, NULL, 9, 'Oiartzun', 'Oiartzun Kalea'),
	(2401, NULL, 9, 'Amasa', 'Amasatarren Kalea'),
	(2406, NULL, 9, 'Astigarraga', 'Astigarraga Kalea'),
	(2502, NULL, 7, 'Jaizkibel', 'Jaizkibel Kalea'),
	(2504, NULL, 7, 'Urdaburu', 'Urdaburu Kalea'),
	(2601, NULL, 7, 'Ernio', 'Ernio Kalea'),
	(2602, NULL, 7, 'Irumugarrieta', 'Irumugarrieta Kalea'),
	(2603, NULL, 7, 'Larrunarri', 'Larrunarri Kalea'),
	(2604, NULL, 7, 'Mandoegi', 'Mandoegi Kalea'),
	(2605, NULL, 7, 'Murumendi', 'Murumendi Kalea'),
	(2701, NULL, 7, 'Aralar Plaza', 'Urbasa Kalea'),
	(2901, NULL, 1, 'Monja Agustindarren Etorbidea', 'Avenida de las Agustinas'),
	(2902, NULL, 1, 'Atarieder', 'Atari Eder Kalea'),
	(2903, NULL, 1, 'Elias Salaberria', 'Elías Salaberria Kalea'),
	(2904, NULL, 1, 'Hombrados Oñatibia', 'Hombrados Oñatibia Kalea'),
	(2905, NULL, 1, 'Markola Etorbidea', 'Markola Etorbidea'),
	(2907, NULL, 1, 'Resurreccion M. Azkue', 'Resurrección María de Azkue Etorbidea'),
	(3001, NULL, 10, 'Olibet', 'Lugar Barrio Olibet, 5'),
	(3201, NULL, 11, 'Arditurri', 'Arditurri Kalea'),
	(3204, NULL, 11, 'Pontika', 'Pontika Kalea'),
	(3402, NULL, 3, 'Jesus Guridi', 'Jesús Guridi Kalea'),
	(3403, NULL, 3, 'Juan C. Arriaga', 'Juan Crisóstomo Arriaga Kalea'),
	(3404, NULL, 3, 'Julian Lavilla', 'Julián Lavilla Kalea'),
	(3405, NULL, 3, 'Norberto Almandoz', 'Norberto Almandoz Kalea'),
	(3501, NULL, 3, 'Beraun', 'Beraun Kalea'),
	(3601, NULL, 3, 'Aita Donostia', 'Aita Donostia Kalea'),
	(3603, NULL, 3, 'Maurice Ravel', 'Maurice Ravel Kalea'),
	(3604, NULL, 3, 'San Marko', 'San Marcos Kalea'),
	(3701, NULL, 3, 'Aldakoenea', 'Aldakoenea Kalea'),
	(3702, NULL, 3, 'Isidro Antsorena', 'Isidro Ansorena Kalea'),
	(3703, NULL, 3, 'Jose M. Usandizaga', 'José María Usandizaga Kalea'),
	(3704, NULL, 3, 'Luis Mariano Plaza', 'Luis Mariano Plaza'),
	(3801, NULL, 4, 'Sorgintzulo', 'Sorgintxulo Kalea'),
	(3901, NULL, 4, 'Basanoaga', 'Basanoaga Kalea'),
	(3903, NULL, 4, 'Versalles', 'Versalles Kalea'),
	(3904, NULL, 4, 'Esnabide', 'Esnabide Kalea'),
	(6001, NULL, 10, 'Gernika Plaza', 'Zubiaurre Kalea'),
	(6002, NULL, 6, 'Evaristo Bozas Plaza', 'Alexander Fleming Kalea'),
	(6003, NULL, 5, 'Zabaleta Anaien Kalea', 'Zabaleta Anaiaren Kalea'),
	(6004, NULL, 7, 'Aiako Harria', 'Aiako Harria Kalea'),
	(6005, NULL, 7, 'Geltokiko Kalea', 'Apeadero Kalea'),
	(6006, NULL, 14, 'San Marko Gunea', 'Camino de San Marcos'),
	(6007, NULL, 14, 'Zentolen Gunea', 'Zentolen Berri'),
	(6008, NULL, 14, 'Zamalbide Gunea', NULL),
	(6009, NULL, 14, 'Aldura Gunea', NULL),
	(6010, NULL, 11, 'Urbasa', 'Calle de Urbasa'),
	(6011, NULL, 4, 'Peninsula Capuchinos', 'Capuchinos Kaia'),
	(6012, NULL, 5, 'Ikutza Kortsarioa', 'Ikutza Korsarioaren Kalea'),
	(6013, NULL, 5, 'Musika Plaza', 'Martín Etxeberria Kalea'),
	(6014, NULL, 5, 'Senidetutako Herrien Plaza / Pueblos Hermanados', 'Urbasa Kalea'),
	(6015, NULL, 4, 'Valverde Antonio, Plaza', NULL),
	(6016, NULL, 4, 'Fuentepelayo Plaza', 'Sorgintxulo Kalea'),
	(6017, NULL, 6, 'Touring Etorbidea', 'Touring Etorbidea'),
	(6018, NULL, 6, 'Dolores Ibarruri Zumardia', 'Dolores Ibárruri Zumardia'),
	(6019, NULL, 6, 'Dario Regoyos', 'Darío Regoyos Kalea'),
	(6020, NULL, 6, 'Garcia Lorca', 'García Lorca Kalea'),
	(6021, NULL, 6, 'Vicente Cobreros', 'Vicente Cobreros Kalea'),
	(6022, NULL, 5, 'Agirre Lehendakariaren Plaza', 'Calle de Abajo'),
	(6023, NULL, 5, 'Andoni Korta', 'Andoni Korta Kalea'),
	(6024, NULL, 5, 'Jaurtarkol Plaza', 'Plaza de Jautarkol'),
	(6025, NULL, 5, 'Xabier Olaskoaga Plaza', 'Xabier Olaskoaga Plaza'),
	(6026, NULL, 10, 'Ugarritza Etorbidea', 'Zubiaurre Kalea'),
	(6027, NULL, 5, 'Zapirain Anaien Kalea', 'Zapirain Anaien Kalea'),
	(6028, NULL, 5, 'Pelotari Kalea', 'Pelotarien Kalea'),
	(6029, NULL, 3, 'Monroy Plaza', 'San Marcos Kalea, 1'),
	(6030, NULL, 11, 'Jose Migel Barandiaran', 'María Lezo Kalea'),
	(6031, NULL, 5, 'Bittor Idiazabal', 'Bittor Idiazabal Kalea'),
	(6032, NULL, 11, 'Tulle', 'Tulle Kalea'),
	(6033, NULL, 1, 'Lousada', 'Lousada Kalea'),
	(6034, NULL, 5, 'Txirrita Parkea', 'Zapirain Anaien Kalea'),
	(6035, NULL, 5, 'Arramendi Pasealekua', 'Tobar Berri Baserria'),
	(6037, NULL, 5, 'Santa Clara, Plaza', NULL),
	(6038, NULL, 3, 'Sarriegi Plaza', 'Sarriegi Plaza'),
	(6039, NULL, 5, 'Gaztelutxo, Parkea', NULL),
	(6040, NULL, 5, 'Urola', 'Urola Kalea'),
	(6041, NULL, 4, 'Zamarreño Jose Manuel, Plaza', NULL),
	(6043, NULL, 1, 'Erramun Astibia', 'Resurrección María de Azkue Etorbidea'),
	(6044, NULL, 11, 'Rioja Glorieta', NULL),
	(6045, NULL, 1, 'Vicente Zapirain', 'Markola Etorbidea'),
	(6046, NULL, 6, 'Bakearen Aldeko Parkea', ' De La Paz Parkea'),
	(6047, NULL, 3, 'Glorieta Extremadura', NULL),
	(6048, NULL, 9, 'Glorieta Galicia', NULL),
	(6049, NULL, 2, 'Glorieta Navarra', NULL),
	(6050, NULL, 3, 'Josep Juni Plaza', 'Josep Juni Plaza'),
	(6051, NULL, 5, 'Rioja, Glorieta', NULL),
	(6052, NULL, 10, 'Glorieta Castilla La Mancha', NULL),
	(6053, NULL, 12, 'Egiburuberri', 'Egiburuberri Pasealekua'),
	(6054, NULL, 8, 'Gaztaño Pasalekua', 'Paseo de Gaztaño'),
	(6055, NULL, 11, 'Arditurri Plaza', 'Arditurri Kalea'),
	(6057, NULL, 14, 'Sagardiburu', NULL),
	(6058, NULL, 14, 'San Marcos carretera', NULL),
	(6060, NULL, 1, 'Jorge Oteiza, Paseo', 'Jorge Oteiza Ibilbidea'),
	(6061, NULL, 14, 'Añabitarte Kalea', 'Anabitarte Bidea'),
	(6063, NULL, 1, 'Glorieta Andalucía', NULL),
	(6064, NULL, 1, 'Parque Eduardo Chillida', NULL),
	(6065, NULL, 11, 'Cataluña, Glorieta', NULL),
	(6066, NULL, 7, 'Parque de Galtzaraborda', NULL),
	(6067, NULL, 14, 'Añabitarte, Villas', NULL),
	(6068, NULL, 14, 'Azeñeta', NULL),
	(9050, NULL, 14, 'Listorreta Gunea', NULL),
	(9051, NULL, 14, 'Zona Añarbe', NULL),
	(21208, NULL, 2, 'Nafarroa Hiribidea 81', 'Nafarroa Etorbidea'),
	(41701, NULL, 4, 'Galtzaraborda Etorbidea 69-105', 'Galtzaraborda Etorbidea'),
	(51208, NULL, 5, 'Nafarroa Hiribidea 23-69', 'Nafarroa Etorbidea'),
	(60361, NULL, 3, 'Pablo Sorozabal Plaza', 'Pablo Sorozabal Plaza'),
	(60431, NULL, 5, 'Galicia, Glorieta', NULL),
	(60451, NULL, 8, 'Parque de Arramendi', 'Arramendi Pasealekua'),
	(60541, NULL, 5, 'Tellerialde Plaza', 'Tellerialde Plaza'),
	(60572, NULL, 2, 'Parque de Alaberga', NULL),
	(60611, NULL, 8, 'Zona de Arramendi', NULL),
	(61208, NULL, 6, 'Nafarroa Hiribidea 2-19', 'Nafarroa Etorbidea'),
	(71701, NULL, 7, 'Galtzaraborda, Avda. de 1-61', 'Galtzaraborda Etorbidea'),
	(91208, NULL, 9, 'Nafarroa Hiribidea 26-32', 'Nafarroa Etorbidea'),
	(101208, NULL, 10, 'Nafarroa Hiribidea s/n,14', 'Nafarroa Etorbidea');

SET foreign_key_checks = 1;
