INSERT INTO `mota` (`id`) VALUES
  (1),
  (2),
  (3),
  (4),
  (5),
  (6),
  (7),
  (8),
  (9),
  (10),
  (11);

INSERT INTO `mota_translation` (`id`, `izena`, `lang`) VALUES
  (1, 'Electricidad', 'es'),
  (1, 'Elektrizitatea', 'eu'),
  (2, 'Pintura', 'es'),
  (2, 'Margolaria', 'eu'),
  (3, 'Carpinteria', 'es'),
  (3, 'Arotza-herramintaria', 'eu'),
  (4, 'Agua', 'es'),
  (4, 'Ura', 'eu'),
  (5, 'Limpieza', 'es'),
  (5, 'Garbiketa', 'eu'),
  (6, 'Jardineria y Montes', 'es'),
  (6, 'Lore eta mendizaintza', 'eu'),
  (7, 'Recogida de basuras', 'es'),
  (7, 'Zabor bilketa', 'eu'),
  (8, 'Sanidad y animales', 'es'),
  (8, 'Osasuna eta animaliak', 'eu'),
  (9, 'Albañilería', 'es'),
  (9, 'Igeltseritza', 'eu'),
  (10, 'Montajes y transportes', 'es'),
  (10, 'Muntaiak eta garraioak', 'eu'),
  (11, 'Gremios varios', 'es'),
  (11, 'Gremio anitz', 'eu');
