SET foreign_key_checks = 0;

TRUNCATE TABLE sf_guard_group;
INSERT INTO `sf_guard_group` (`id`, `description`, `created_at`, `updated_at`) VALUES
  (1, NULL, NULL, NULL),
  (2, NULL, NULL, NULL),
  (3, NULL, NULL, NULL),
  (4, NULL, NULL, NULL),
  (5, NULL, NULL, NULL),
  (6, NULL, NULL, NULL),
  (7, NULL, NULL, NULL),
  (8, NULL, NULL, NULL),
  (9, NULL, NULL, NULL),
  (10, NULL, NULL, NULL),
  (11, NULL, NULL, NULL),
  (12, NULL, NULL, NULL),
  (13, NULL, NULL, NULL),
  (14, NULL, NULL, NULL),
  (15, NULL, NULL, NULL),
  (16, NULL, NULL, NULL),
  (17, NULL, NULL, NULL);

TRUNCATE TABLE sf_guard_group_translation;
INSERT INTO `sf_guard_group_translation` (`id`, `name`, `lang`) VALUES
  (1, 'Electricidad', 'es'),
  (1, 'Elektrizitatea', 'eu'),
  (2, 'Pintura', 'es'),
  (2, 'Margolaria', 'eu'),
  (3, 'Carpinteria', 'es'),
  (3, 'Arotza', 'eu'),
  (4, 'Agua', 'es'),
  (4, 'Ura', 'eu'),
  (5, 'Limpieza', 'es'),
  (5, 'Garbiketa', 'eu'),
  (6, 'Jardineria y Montes', 'es'),
  (6, 'Lore eta mendizaintza', 'eu'),
  (7, 'Herreria', 'es'),
  (7, 'Errementeria', 'eu'),
  (8, 'Volante', 'es'),
  (8, 'Ibiltaria', 'eu'),
  (9, 'Obras', 'es'),
  (9, 'Herri-lanak', 'eu'),
  (10, 'Actividades', 'es'),
  (10, 'Ekintzak', 'eu'),
  (11, 'Gremios varios', 'es'),
  (11, 'Gremio anitz', 'eu'),
  (12, 'Asfaltado', 'es'),
  (12, 'Asfaltatzea', 'eu'),
  (13, 'Tráfico y transportes', 'es'),
  (13, 'Trafikoa eta garraioak', 'eu'),
  (14, 'Informática', 'es'),
  (14, 'Informatika', 'eu'),
  (15, 'PL Coordinación Urbanística', 'es'),
  (15, 'U. Hiri Koordinazioa', 'eu'),
  (16, 'Señalización', 'es'),
  (16, 'Seinalizazioa', 'eu'),
  (17, 'Otros', 'es'),
  (17, 'Besteak', 'eu');

SET foreign_key_checks = 1;
