<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Langilea', 'doctrine');

/**
 * BaseLangilea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Ohartaraztea $Ohartaraztea
 * @property Doctrine_Collection $Gertakaria
 * @property Doctrine_Collection $Fitxategia
 * @property Doctrine_Collection $Iruzkina
 * @property Doctrine_Collection $Planifikazioa
 * 
 * @method Ohartaraztea        getOhartaraztea()  Returns the current record's "Ohartaraztea" value
 * @method Doctrine_Collection getGertakaria()    Returns the current record's "Gertakaria" collection
 * @method Doctrine_Collection getFitxategia()    Returns the current record's "Fitxategia" collection
 * @method Doctrine_Collection getIruzkina()      Returns the current record's "Iruzkina" collection
 * @method Doctrine_Collection getPlanifikazioa() Returns the current record's "Planifikazioa" collection
 * @method Langilea            setOhartaraztea()  Sets the current record's "Ohartaraztea" value
 * @method Langilea            setGertakaria()    Sets the current record's "Gertakaria" collection
 * @method Langilea            setFitxategia()    Sets the current record's "Fitxategia" collection
 * @method Langilea            setIruzkina()      Sets the current record's "Iruzkina" collection
 * @method Langilea            setPlanifikazioa() Sets the current record's "Planifikazioa" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLangilea extends sfGuardUser
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ohartaraztea', array(
             'local' => 'ohartaraztea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'langilea_id'));

        $this->hasMany('Fitxategia', array(
             'local' => 'id',
             'foreign' => 'langilea_id'));

        $this->hasMany('Iruzkina', array(
             'local' => 'id',
             'foreign' => 'langilea_id'));

        $this->hasMany('Planifikazioa', array(
             'local' => 'id',
             'foreign' => 'langilea_id'));
    }
}