<?php

/**
 * BaseKontaktuaOhartaraztea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ordena
 * @property string $modua
 * @property Doctrine_Collection $Kontaktua
 * 
 * @method integer               getOrdena()    Returns the current record's "ordena" value
 * @method string                getModua()     Returns the current record's "modua" value
 * @method Doctrine_Collection   getKontaktua() Returns the current record's "Kontaktua" collection
 * @method KontaktuaOhartaraztea setOrdena()    Sets the current record's "ordena" value
 * @method KontaktuaOhartaraztea setModua()     Sets the current record's "modua" value
 * @method KontaktuaOhartaraztea setKontaktua() Sets the current record's "Kontaktua" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKontaktuaOhartaraztea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kontaktua_ohartaraztea');
        $this->hasColumn('ordena', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('modua', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Kontaktua', array(
             'local' => 'id',
             'foreign' => 'ohartarazi'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'modua',
             ),
             ));
        $this->actAs($i18n0);
    }
}