<?php

/**
 * BaseGertakaria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $laburpena
 * @property integer $klasea_id
 * @property integer $mota_id
 * @property integer $azpimota_id
 * @property string $abisuaNork
 * @property integer $egoera_id
 * @property integer $saila_id
 * @property integer $langilea_id
 * @property integer $barrutia_id
 * @property integer $auzoa_id
 * @property integer $kalea_id
 * @property string $kale_zbkia
 * @property string $deskribapena
 * @property timestamp $ixte_data
 * @property date $hasiera_aurreikusia
 * @property date $amaiera_aurreikusia
 * @property integer $lehentasuna_id
 * @property integer $jatorrizkoSaila_id
 * @property integer $eraikina_id
 * @property boolean $herritarrena
 * @property integer $kontaktua_id
 * @property string $espedientea
 * @property Klasea $Klasea
 * @property Mota $Mota
 * @property Azpimota $Azpimota
 * @property Barrutia $Barrutia
 * @property Auzoa $Auzoa
 * @property Kalea $Kalea
 * @property Saila $Saila
 * @property Langilea $Langilea
 * @property Egoera $Egoera
 * @property Lehentasuna $Lehentasuna
 * @property JatorrizkoSaila $JatorrizkoSaila
 * @property Eraikina $Eraikina
 * @property Kontaktua $Kontaktua
 * @property Doctrine_Collection $Fitxategia
 * @property Doctrine_Collection $Iruzkina
 * @property Doctrine_Collection $Planifikazioa
 * @property Doctrine_Collection $Geo
 * @property Doctrine_Collection $Erlazioak
 * 
 * @method string              getLaburpena()           Returns the current record's "laburpena" value
 * @method integer             getKlaseaId()            Returns the current record's "klasea_id" value
 * @method integer             getMotaId()              Returns the current record's "mota_id" value
 * @method integer             getAzpimotaId()          Returns the current record's "azpimota_id" value
 * @method string              getAbisuaNork()          Returns the current record's "abisuaNork" value
 * @method integer             getEgoeraId()            Returns the current record's "egoera_id" value
 * @method integer             getSailaId()             Returns the current record's "saila_id" value
 * @method integer             getLangileaId()          Returns the current record's "langilea_id" value
 * @method integer             getBarrutiaId()          Returns the current record's "barrutia_id" value
 * @method integer             getAuzoaId()             Returns the current record's "auzoa_id" value
 * @method integer             getKaleaId()             Returns the current record's "kalea_id" value
 * @method string              getKaleZbkia()           Returns the current record's "kale_zbkia" value
 * @method string              getDeskribapena()        Returns the current record's "deskribapena" value
 * @method timestamp           getIxteData()            Returns the current record's "ixte_data" value
 * @method date                getHasieraAurreikusia()  Returns the current record's "hasiera_aurreikusia" value
 * @method date                getAmaieraAurreikusia()  Returns the current record's "amaiera_aurreikusia" value
 * @method integer             getLehentasunaId()       Returns the current record's "lehentasuna_id" value
 * @method integer             getJatorrizkoSailaId()   Returns the current record's "jatorrizkoSaila_id" value
 * @method integer             getEraikinaId()          Returns the current record's "eraikina_id" value
 * @method boolean             getHerritarrena()        Returns the current record's "herritarrena" value
 * @method integer             getKontaktuaId()         Returns the current record's "kontaktua_id" value
 * @method string              getEspedientea()         Returns the current record's "espedientea" value
 * @method Klasea              getKlasea()              Returns the current record's "Klasea" value
 * @method Mota                getMota()                Returns the current record's "Mota" value
 * @method Azpimota            getAzpimota()            Returns the current record's "Azpimota" value
 * @method Barrutia            getBarrutia()            Returns the current record's "Barrutia" value
 * @method Auzoa               getAuzoa()               Returns the current record's "Auzoa" value
 * @method Kalea               getKalea()               Returns the current record's "Kalea" value
 * @method Saila               getSaila()               Returns the current record's "Saila" value
 * @method Langilea            getLangilea()            Returns the current record's "Langilea" value
 * @method Egoera              getEgoera()              Returns the current record's "Egoera" value
 * @method Lehentasuna         getLehentasuna()         Returns the current record's "Lehentasuna" value
 * @method JatorrizkoSaila     getJatorrizkoSaila()     Returns the current record's "JatorrizkoSaila" value
 * @method Eraikina            getEraikina()            Returns the current record's "Eraikina" value
 * @method Kontaktua           getKontaktua()           Returns the current record's "Kontaktua" value
 * @method Doctrine_Collection getFitxategia()          Returns the current record's "Fitxategia" collection
 * @method Doctrine_Collection getIruzkina()            Returns the current record's "Iruzkina" collection
 * @method Doctrine_Collection getPlanifikazioa()       Returns the current record's "Planifikazioa" collection
 * @method Doctrine_Collection getGeo()                 Returns the current record's "Geo" collection
 * @method Doctrine_Collection getErlazioak()           Returns the current record's "Erlazioak" collection
 * @method Gertakaria          setLaburpena()           Sets the current record's "laburpena" value
 * @method Gertakaria          setKlaseaId()            Sets the current record's "klasea_id" value
 * @method Gertakaria          setMotaId()              Sets the current record's "mota_id" value
 * @method Gertakaria          setAzpimotaId()          Sets the current record's "azpimota_id" value
 * @method Gertakaria          setAbisuaNork()          Sets the current record's "abisuaNork" value
 * @method Gertakaria          setEgoeraId()            Sets the current record's "egoera_id" value
 * @method Gertakaria          setSailaId()             Sets the current record's "saila_id" value
 * @method Gertakaria          setLangileaId()          Sets the current record's "langilea_id" value
 * @method Gertakaria          setBarrutiaId()          Sets the current record's "barrutia_id" value
 * @method Gertakaria          setAuzoaId()             Sets the current record's "auzoa_id" value
 * @method Gertakaria          setKaleaId()             Sets the current record's "kalea_id" value
 * @method Gertakaria          setKaleZbkia()           Sets the current record's "kale_zbkia" value
 * @method Gertakaria          setDeskribapena()        Sets the current record's "deskribapena" value
 * @method Gertakaria          setIxteData()            Sets the current record's "ixte_data" value
 * @method Gertakaria          setHasieraAurreikusia()  Sets the current record's "hasiera_aurreikusia" value
 * @method Gertakaria          setAmaieraAurreikusia()  Sets the current record's "amaiera_aurreikusia" value
 * @method Gertakaria          setLehentasunaId()       Sets the current record's "lehentasuna_id" value
 * @method Gertakaria          setJatorrizkoSailaId()   Sets the current record's "jatorrizkoSaila_id" value
 * @method Gertakaria          setEraikinaId()          Sets the current record's "eraikina_id" value
 * @method Gertakaria          setHerritarrena()        Sets the current record's "herritarrena" value
 * @method Gertakaria          setKontaktuaId()         Sets the current record's "kontaktua_id" value
 * @method Gertakaria          setEspedientea()         Sets the current record's "espedientea" value
 * @method Gertakaria          setKlasea()              Sets the current record's "Klasea" value
 * @method Gertakaria          setMota()                Sets the current record's "Mota" value
 * @method Gertakaria          setAzpimota()            Sets the current record's "Azpimota" value
 * @method Gertakaria          setBarrutia()            Sets the current record's "Barrutia" value
 * @method Gertakaria          setAuzoa()               Sets the current record's "Auzoa" value
 * @method Gertakaria          setKalea()               Sets the current record's "Kalea" value
 * @method Gertakaria          setSaila()               Sets the current record's "Saila" value
 * @method Gertakaria          setLangilea()            Sets the current record's "Langilea" value
 * @method Gertakaria          setEgoera()              Sets the current record's "Egoera" value
 * @method Gertakaria          setLehentasuna()         Sets the current record's "Lehentasuna" value
 * @method Gertakaria          setJatorrizkoSaila()     Sets the current record's "JatorrizkoSaila" value
 * @method Gertakaria          setEraikina()            Sets the current record's "Eraikina" value
 * @method Gertakaria          setKontaktua()           Sets the current record's "Kontaktua" value
 * @method Gertakaria          setFitxategia()          Sets the current record's "Fitxategia" collection
 * @method Gertakaria          setIruzkina()            Sets the current record's "Iruzkina" collection
 * @method Gertakaria          setPlanifikazioa()       Sets the current record's "Planifikazioa" collection
 * @method Gertakaria          setGeo()                 Sets the current record's "Geo" collection
 * @method Gertakaria          setErlazioak()           Sets the current record's "Erlazioak" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGertakaria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gertakaria');
        $this->hasColumn('laburpena', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('klasea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('mota_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('azpimota_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('abisuaNork', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('egoera_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('saila_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('langilea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('barrutia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('auzoa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('kalea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('kale_zbkia', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('deskribapena', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('ixte_data', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('hasiera_aurreikusia', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('amaiera_aurreikusia', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('lehentasuna_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('jatorrizkoSaila_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('eraikina_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('herritarrena', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('kontaktua_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('espedientea', 'string', 12, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 12,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Klasea', array(
             'local' => 'klasea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Mota', array(
             'local' => 'mota_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Azpimota', array(
             'local' => 'azpimota_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Barrutia', array(
             'local' => 'barrutia_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Auzoa', array(
             'local' => 'auzoa_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Kalea', array(
             'local' => 'kalea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Saila', array(
             'local' => 'saila_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Langilea', array(
             'local' => 'langilea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Egoera', array(
             'local' => 'egoera_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Lehentasuna', array(
             'local' => 'lehentasuna_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('JatorrizkoSaila', array(
             'local' => 'jatorrizkoSaila_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Eraikina', array(
             'local' => 'eraikina_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Kontaktua', array(
             'local' => 'kontaktua_id',
             'foreign' => 'id'));

        $this->hasMany('Fitxategia', array(
             'local' => 'id',
             'foreign' => 'gertakaria_id'));

        $this->hasMany('Iruzkina', array(
             'local' => 'id',
             'foreign' => 'gertakaria_id'));

        $this->hasMany('Planifikazioa', array(
             'local' => 'id',
             'foreign' => 'gertakaria_id'));

        $this->hasMany('Geo', array(
             'local' => 'id',
             'foreign' => 'gertakaria_id'));

        $this->hasMany('Erlazioak', array(
             'local' => 'id',
             'foreign' => 'amaiera_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}