<?php

/**
 * BasePlanifikazioa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int            $gertakaria_id                       Type: integer
 * @property int            $langilea_id                         Type: integer
 * @property string         $hasiera_data                        Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property string         $hasiera_ordua_noiztik               Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @property string         $hasiera_ordua_noizarte              Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @property string         $amaiera_data                        Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property string         $amaiera_ordua_noiztik               Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @property string         $amaiera_ordua_noizarte              Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @property Gertakaria     $Gertakaria                          
 * @property Langilea       $Langilea                            
 *  
 * @method int              getGertakariaId()                    Type: integer
 * @method int              getLangileaId()                      Type: integer
 * @method string           getHasieraData()                     Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method string           getHasieraOrduaNoiztik()             Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @method string           getHasieraOrduaNoizarte()            Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @method string           getAmaieraData()                     Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method string           getAmaieraOrduaNoiztik()             Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @method string           getAmaieraOrduaNoizarte()            Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @method Gertakaria       getGertakaria()                      
 * @method Langilea         getLangilea()                        
 *  
 * @method Planifikazioa    setGertakariaId(int $val)            Type: integer
 * @method Planifikazioa    setLangileaId(int $val)              Type: integer
 * @method Planifikazioa    setHasieraData(string $val)          Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Planifikazioa    setHasieraOrduaNoiztik(string $val)  Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @method Planifikazioa    setHasieraOrduaNoizarte(string $val) Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @method Planifikazioa    setAmaieraData(string $val)          Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Planifikazioa    setAmaieraOrduaNoiztik(string $val)  Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @method Planifikazioa    setAmaieraOrduaNoizarte(string $val) Type: time, Time in ISO-8601 format (HH:MI:SS)
 * @method Planifikazioa    setGertakaria(Gertakaria $val)       
 * @method Planifikazioa    setLangilea(Langilea $val)           
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlanifikazioa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('planifikazioa');
        $this->hasColumn('gertakaria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('langilea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('hasiera_data', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hasiera_ordua_noiztik', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('hasiera_ordua_noizarte', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('amaiera_data', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('amaiera_ordua_noiztik', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('amaiera_ordua_noizarte', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gertakaria', array(
             'local' => 'gertakaria_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Langilea', array(
             'local' => 'langilea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}