<?php

/**
 * BaseAzpimota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mota_id
 * @property string $izena
 * @property Mota $Mota
 * @property Doctrine_Collection $Gertakaria
 * 
 * @method integer             getMotaId()     Returns the current record's "mota_id" value
 * @method string              getIzena()      Returns the current record's "izena" value
 * @method Mota                getMota()       Returns the current record's "Mota" value
 * @method Doctrine_Collection getGertakaria() Returns the current record's "Gertakaria" collection
 * @method Azpimota            setMotaId()     Sets the current record's "mota_id" value
 * @method Azpimota            setIzena()      Sets the current record's "izena" value
 * @method Azpimota            setMota()       Sets the current record's "Mota" value
 * @method Azpimota            setGertakaria() Sets the current record's "Gertakaria" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAzpimota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('azpimota');
        $this->hasColumn('mota_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mota', array(
             'local' => 'mota_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'azpimota_id'));
    }
}