<?php

/**
 * BaseGeometria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $mota
 * @property Doctrine_Collection $Geo
 * 
 * @method string              getMota() Returns the current record's "mota" value
 * @method Doctrine_Collection getGeo()  Returns the current record's "Geo" collection
 * @method Geometria           setMota() Sets the current record's "mota" value
 * @method Geometria           setGeo()  Sets the current record's "Geo" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeometria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('geometria');
        $this->hasColumn('mota', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Geo', array(
             'local' => 'id',
             'foreign' => 'geometria_id'));
    }
}