<?php

/**
 * BaseAuzoa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $barrutia_id
 * @property string $izena
 * @property Barrutia $Barrutia
 * @property Doctrine_Collection $Gertakaria
 * @property Doctrine_Collection $Kalea
 * @property Doctrine_Collection $Eraikina
 * 
 * @method integer             getBarrutiaId()  Returns the current record's "barrutia_id" value
 * @method string              getIzena()       Returns the current record's "izena" value
 * @method Barrutia            getBarrutia()    Returns the current record's "Barrutia" value
 * @method Doctrine_Collection getGertakaria()  Returns the current record's "Gertakaria" collection
 * @method Doctrine_Collection getKalea()       Returns the current record's "Kalea" collection
 * @method Doctrine_Collection getEraikina()    Returns the current record's "Eraikina" collection
 * @method Auzoa               setBarrutiaId()  Sets the current record's "barrutia_id" value
 * @method Auzoa               setIzena()       Sets the current record's "izena" value
 * @method Auzoa               setBarrutia()    Sets the current record's "Barrutia" value
 * @method Auzoa               setGertakaria()  Sets the current record's "Gertakaria" collection
 * @method Auzoa               setKalea()       Sets the current record's "Kalea" collection
 * @method Auzoa               setEraikina()    Sets the current record's "Eraikina" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuzoa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('auzoa');
        $this->hasColumn('barrutia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Barrutia', array(
             'local' => 'barrutia_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'auzoa_id'));

        $this->hasMany('Kalea', array(
             'local' => 'id',
             'foreign' => 'auzoa_id'));

        $this->hasMany('Eraikina', array(
             'local' => 'id',
             'foreign' => 'auzoa_id'));
    }
}