<?php

/**
 * BaseOhartaraztea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                          $mota                                 Type: string(255)
 * @property Doctrine_Collection|Langilea[]  $Langilea                             
 *  
 * @method string                            getMota()                             Type: string(255)
 * @method Doctrine_Collection|Langilea[]    getLangilea()                         
 *  
 * @method Ohartaraztea                      setMota(string $val)                  Type: string(255)
 * @method Ohartaraztea                      setLangilea(Doctrine_Collection $val) 
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhartaraztea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohartaraztea');
        $this->hasColumn('mota', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Langilea', array(
             'local' => 'id',
             'foreign' => 'ohartaraztea_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'mota',
             ),
             ));
        $this->actAs($i18n0);
    }
}