<?php

/**
 * BaseGertakaria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                               $laburpena                                 Type: string(255)
 * @property int                                  $klasea_id                                 Type: integer
 * @property int                                  $arloa_id                                  Type: integer
 * @property int                                  $mota_id                                   Type: integer
 * @property int                                  $azpimota_id                               Type: integer
 * @property string                               $abisuaNork                                Type: string(512)
 * @property int                                  $egoera_id                                 Type: integer, default "1"
 * @property int                                  $saila_id                                  Type: integer
 * @property int                                  $langilea_id                               Type: integer
 * @property int                                  $barrutia_id                               Type: integer
 * @property int                                  $auzoa_id                                  Type: integer
 * @property int                                  $kalea_id                                  Type: integer
 * @property string                               $kale_zbkia                                Type: string(50)
 * @property string                               $deskribapena                              Type: string(4000)
 * @property string                               $ixte_data                                 Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                               $hasiera_aurreikusia                       Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property string                               $amaiera_aurreikusia                       Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property int                                  $lehentasuna_id                            Type: integer
 * @property int                                  $jatorrizkoSaila_id                        Type: integer
 * @property int                                  $eraikina_id                               Type: integer
 * @property int                                  $herritarrena                              Type: integer
 * @property int                                  $kontaktua_id                              Type: integer
 * @property string                               $espedientea                               Type: string(12)
 * @property Klasea                               $Klasea                                    
 * @property Arloa                                $Arloa                                     
 * @property Mota                                 $Mota                                      
 * @property Azpimota                             $Azpimota                                  
 * @property Barrutia                             $Barrutia                                  
 * @property Auzoa                                $Auzoa                                     
 * @property Kalea                                $Kalea                                     
 * @property Saila                                $Saila                                     
 * @property Langilea                             $Langilea                                  
 * @property Egoera                               $Egoera                                    
 * @property Lehentasuna                          $Lehentasuna                               
 * @property JatorrizkoSaila                      $JatorrizkoSaila                           
 * @property Eraikina                             $Eraikina                                  
 * @property Kontaktua                            $Kontaktua                                 
 * @property Doctrine_Collection|Fitxategia[]     $Fitxategia                                
 * @property Doctrine_Collection|Iruzkina[]       $Iruzkina                                  
 * @property Doctrine_Collection|Planifikazioa[]  $Planifikazioa                             
 * @property Doctrine_Collection|Geo[]            $Geo                                       
 * @property Doctrine_Collection|Erlazioak[]      $Erlazioak                                 
 *  
 * @method string                                 getLaburpena()                             Type: string(255)
 * @method int                                    getKlaseaId()                              Type: integer
 * @method int                                    getArloaId()                               Type: integer
 * @method int                                    getMotaId()                                Type: integer
 * @method int                                    getAzpimotaId()                            Type: integer
 * @method string                                 getAbisuanork()                            Type: string(512)
 * @method int                                    getEgoeraId()                              Type: integer, default "1"
 * @method int                                    getSailaId()                               Type: integer
 * @method int                                    getLangileaId()                            Type: integer
 * @method int                                    getBarrutiaId()                            Type: integer
 * @method int                                    getAuzoaId()                               Type: integer
 * @method int                                    getKaleaId()                               Type: integer
 * @method string                                 getKaleZbkia()                             Type: string(50)
 * @method string                                 getDeskribapena()                          Type: string(4000)
 * @method string                                 getIxteData()                              Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                                 getHasieraAurreikusia()                    Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method string                                 getAmaieraAurreikusia()                    Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method int                                    getLehentasunaId()                         Type: integer
 * @method int                                    getJatorrizkosailaId()                     Type: integer
 * @method int                                    getEraikinaId()                            Type: integer
 * @method int                                    getHerritarrena()                          Type: integer
 * @method int                                    getKontaktuaId()                           Type: integer
 * @method string                                 getEspedientea()                           Type: string(12)
 * @method Klasea                                 getKlasea()                                
 * @method Arloa                                  getArloa()                                 
 * @method Mota                                   getMota()                                  
 * @method Azpimota                               getAzpimota()                              
 * @method Barrutia                               getBarrutia()                              
 * @method Auzoa                                  getAuzoa()                                 
 * @method Kalea                                  getKalea()                                 
 * @method Saila                                  getSaila()                                 
 * @method Langilea                               getLangilea()                              
 * @method Egoera                                 getEgoera()                                
 * @method Lehentasuna                            getLehentasuna()                           
 * @method JatorrizkoSaila                        getJatorrizkoSaila()                       
 * @method Eraikina                               getEraikina()                              
 * @method Kontaktua                              getKontaktua()                             
 * @method Doctrine_Collection|Fitxategia[]       getFitxategia()                            
 * @method Doctrine_Collection|Iruzkina[]         getIruzkina()                              
 * @method Doctrine_Collection|Planifikazioa[]    getPlanifikazioa()                         
 * @method Doctrine_Collection|Geo[]              getGeo()                                   
 * @method Doctrine_Collection|Erlazioak[]        getErlazioak()                             
 *  
 * @method Gertakaria                             setLaburpena(string $val)                  Type: string(255)
 * @method Gertakaria                             setKlaseaId(int $val)                      Type: integer
 * @method Gertakaria                             setArloaId(int $val)                       Type: integer
 * @method Gertakaria                             setMotaId(int $val)                        Type: integer
 * @method Gertakaria                             setAzpimotaId(int $val)                    Type: integer
 * @method Gertakaria                             setAbisuanork(string $val)                 Type: string(512)
 * @method Gertakaria                             setEgoeraId(int $val)                      Type: integer, default "1"
 * @method Gertakaria                             setSailaId(int $val)                       Type: integer
 * @method Gertakaria                             setLangileaId(int $val)                    Type: integer
 * @method Gertakaria                             setBarrutiaId(int $val)                    Type: integer
 * @method Gertakaria                             setAuzoaId(int $val)                       Type: integer
 * @method Gertakaria                             setKaleaId(int $val)                       Type: integer
 * @method Gertakaria                             setKaleZbkia(string $val)                  Type: string(50)
 * @method Gertakaria                             setDeskribapena(string $val)               Type: string(4000)
 * @method Gertakaria                             setIxteData(string $val)                   Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method Gertakaria                             setHasieraAurreikusia(string $val)         Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Gertakaria                             setAmaieraAurreikusia(string $val)         Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Gertakaria                             setLehentasunaId(int $val)                 Type: integer
 * @method Gertakaria                             setJatorrizkosailaId(int $val)             Type: integer
 * @method Gertakaria                             setEraikinaId(int $val)                    Type: integer
 * @method Gertakaria                             setHerritarrena(int $val)                  Type: integer
 * @method Gertakaria                             setKontaktuaId(int $val)                   Type: integer
 * @method Gertakaria                             setEspedientea(string $val)                Type: string(12)
 * @method Gertakaria                             setKlasea(Klasea $val)                     
 * @method Gertakaria                             setArloa(Arloa $val)                       
 * @method Gertakaria                             setMota(Mota $val)                         
 * @method Gertakaria                             setAzpimota(Azpimota $val)                 
 * @method Gertakaria                             setBarrutia(Barrutia $val)                 
 * @method Gertakaria                             setAuzoa(Auzoa $val)                       
 * @method Gertakaria                             setKalea(Kalea $val)                       
 * @method Gertakaria                             setSaila(Saila $val)                       
 * @method Gertakaria                             setLangilea(Langilea $val)                 
 * @method Gertakaria                             setEgoera(Egoera $val)                     
 * @method Gertakaria                             setLehentasuna(Lehentasuna $val)           
 * @method Gertakaria                             setJatorrizkoSaila(JatorrizkoSaila $val)   
 * @method Gertakaria                             setEraikina(Eraikina $val)                 
 * @method Gertakaria                             setKontaktua(Kontaktua $val)               
 * @method Gertakaria                             setFitxategia(Doctrine_Collection $val)    
 * @method Gertakaria                             setIruzkina(Doctrine_Collection $val)      
 * @method Gertakaria                             setPlanifikazioa(Doctrine_Collection $val) 
 * @method Gertakaria                             setGeo(Doctrine_Collection $val)           
 * @method Gertakaria                             setErlazioak(Doctrine_Collection $val)     
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGertakaria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gertakaria');
        $this->hasColumn('laburpena', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('klasea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('arloa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('mota_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('azpimota_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('abisuaNork', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('egoera_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('saila_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('langilea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('barrutia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('auzoa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('kalea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('kale_zbkia', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('deskribapena', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('ixte_data', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('hasiera_aurreikusia', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('amaiera_aurreikusia', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('lehentasuna_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('jatorrizkoSaila_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('eraikina_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('herritarrena', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('kontaktua_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('espedientea', 'string', 12, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 12,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Klasea', array(
             'local' => 'klasea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Arloa', array(
             'local' => 'arloa_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Mota', array(
             'local' => 'mota_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Azpimota', array(
             'local' => 'azpimota_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Barrutia', array(
             'local' => 'barrutia_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Auzoa', array(
             'local' => 'auzoa_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Kalea', array(
             'local' => 'kalea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Saila', array(
             'local' => 'saila_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Langilea', array(
             'local' => 'langilea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Egoera', array(
             'local' => 'egoera_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Lehentasuna', array(
             'local' => 'lehentasuna_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('JatorrizkoSaila', array(
             'local' => 'jatorrizkoSaila_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Eraikina', array(
             'local' => 'eraikina_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Kontaktua', array(
             'local' => 'kontaktua_id',
             'foreign' => 'id'));

        $this->hasMany('Fitxategia', array(
             'local' => 'id',
             'foreign' => 'gertakaria_id'));

        $this->hasMany('Iruzkina', array(
             'local' => 'id',
             'foreign' => 'gertakaria_id'));

        $this->hasMany('Planifikazioa', array(
             'local' => 'id',
             'foreign' => 'gertakaria_id'));

        $this->hasMany('Geo', array(
             'local' => 'id',
             'foreign' => 'gertakaria_id'));

        $this->hasMany('Erlazioak', array(
             'local' => 'id',
             'foreign' => 'amaiera_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}