<?php

/**
 * BaseOhartarazteMota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $mota
 * @property Doctrine_Collection $Langilea
 * 
 * @method string              getMota()     Returns the current record's "mota" value
 * @method Doctrine_Collection getLangilea() Returns the current record's "Langilea" collection
 * @method OhartarazteMota     setMota()     Sets the current record's "mota" value
 * @method OhartarazteMota     setLangilea() Sets the current record's "Langilea" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhartarazteMota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohartarazte_mota');
        $this->hasColumn('mota', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Langilea', array(
             'local' => 'id',
             'foreign' => 'ohartarazteMota_id'));
    }
}