<?php

/**
 * BaseKontaktua
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $izena
 * @property string $abizenak
 * @property string $nan
 * @property string $posta
 * @property string $telefonoa
 * @property integer $ohartarazi
 * @property string $hizkuntza
 * @property KontaktuaOhartaraztea $KontaktuaOhartaraztea
 * @property Gertakaria $Gertakaria
 * 
 * @method string                getIzena()                 Returns the current record's "izena" value
 * @method string                getAbizenak()              Returns the current record's "abizenak" value
 * @method string                getNan()                   Returns the current record's "nan" value
 * @method string                getPosta()                 Returns the current record's "posta" value
 * @method string                getTelefonoa()             Returns the current record's "telefonoa" value
 * @method integer               getOhartarazi()            Returns the current record's "ohartarazi" value
 * @method string                getHizkuntza()             Returns the current record's "hizkuntza" value
 * @method KontaktuaOhartaraztea getKontaktuaOhartaraztea() Returns the current record's "KontaktuaOhartaraztea" value
 * @method Gertakaria            getGertakaria()            Returns the current record's "Gertakaria" value
 * @method Kontaktua             setIzena()                 Sets the current record's "izena" value
 * @method Kontaktua             setAbizenak()              Sets the current record's "abizenak" value
 * @method Kontaktua             setNan()                   Sets the current record's "nan" value
 * @method Kontaktua             setPosta()                 Sets the current record's "posta" value
 * @method Kontaktua             setTelefonoa()             Sets the current record's "telefonoa" value
 * @method Kontaktua             setOhartarazi()            Sets the current record's "ohartarazi" value
 * @method Kontaktua             setHizkuntza()             Sets the current record's "hizkuntza" value
 * @method Kontaktua             setKontaktuaOhartaraztea() Sets the current record's "KontaktuaOhartaraztea" value
 * @method Kontaktua             setGertakaria()            Sets the current record's "Gertakaria" value
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKontaktua extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kontaktua');
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('abizenak', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('nan', 'string', 9, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 9,
             ));
        $this->hasColumn('posta', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('telefonoa', 'string', 30, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 30,
             ));
        $this->hasColumn('ohartarazi', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('hizkuntza', 'string', 2, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('KontaktuaOhartaraztea', array(
             'local' => 'ohartarazi',
             'foreign' => 'id'));

        $this->hasOne('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'kontaktua_id'));
    }
}