<?php

/**
 * BaseFitxategia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int         $gertakaria_id                 Type: integer
 * @property int         $langilea_id                   Type: integer
 * @property string      $fitxategia                    Type: string(255)
 * @property string      $deskribapena                  Type: string(255)
 * @property Gertakaria  $Gertakaria                    
 * @property Langilea    $Langilea                      
 *  
 * @method int           getGertakariaId()              Type: integer
 * @method int           getLangileaId()                Type: integer
 * @method string        getFitxategia()                Type: string(255)
 * @method string        getDeskribapena()              Type: string(255)
 * @method Gertakaria    getGertakaria()                
 * @method Langilea      getLangilea()                  
 *  
 * @method Fitxategia    setGertakariaId(int $val)      Type: integer
 * @method Fitxategia    setLangileaId(int $val)        Type: integer
 * @method Fitxategia    setFitxategia(string $val)     Type: string(255)
 * @method Fitxategia    setDeskribapena(string $val)   Type: string(255)
 * @method Fitxategia    setGertakaria(Gertakaria $val) 
 * @method Fitxategia    setLangilea(Langilea $val)     
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFitxategia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fitxategia');
        $this->hasColumn('gertakaria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('langilea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('fitxategia', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('deskribapena', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gertakaria', array(
             'local' => 'gertakaria_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Langilea', array(
             'local' => 'langilea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}