<?php

/**
 * BaseLehentasuna
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                            $izena                                  Type: string(255), unique
 * @property string                            $kolorea                                Type: string(50)
 * @property Doctrine_Collection|Gertakaria[]  $Gertakaria                             
 *  
 * @method string                              getIzena()                              Type: string(255), unique
 * @method string                              getKolorea()                            Type: string(50)
 * @method Doctrine_Collection|Gertakaria[]    getGertakaria()                         
 *  
 * @method Lehentasuna                         setIzena(string $val)                   Type: string(255), unique
 * @method Lehentasuna                         setKolorea(string $val)                 Type: string(50)
 * @method Lehentasuna                         setGertakaria(Doctrine_Collection $val) 
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLehentasuna extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lehentasuna');
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('kolorea', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'lehentasuna_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'izena',
             ),
             ));
        $this->actAs($i18n0);
    }
}