<?php

/**
 * BaseErlazioMota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $izena
 * @property Doctrine_Collection $Erlazioak
 * 
 * @method string              getIzena()     Returns the current record's "izena" value
 * @method Doctrine_Collection getErlazioak() Returns the current record's "Erlazioak" collection
 * @method ErlazioMota         setIzena()     Sets the current record's "izena" value
 * @method ErlazioMota         setErlazioak() Sets the current record's "Erlazioak" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseErlazioMota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('erlazio_mota');
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Erlazioak', array(
             'local' => 'id',
             'foreign' => 'erlazio_mota_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'izena',
             ),
             ));
        $this->actAs($i18n0);
    }
}