<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Saila', 'doctrine');

/**
 * BaseSaila
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Gertakaria
 * 
 * @method Doctrine_Collection getGertakaria() Returns the current record's "Gertakaria" collection
 * @method Saila               setGertakaria() Sets the current record's "Gertakaria" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSaila extends sfGuardGroup
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'saila_id'));
    }
}