<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Langilea', 'doctrine');

/**
 * BaseLangilea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Ohartaraztea                         $Ohartaraztea                              
 * @property Doctrine_Collection|Gertakaria[]     $Gertakaria                                
 * @property Doctrine_Collection|Fitxategia[]     $Fitxategia                                
 * @property Doctrine_Collection|Iruzkina[]       $Iruzkina                                  
 * @property Doctrine_Collection|Planifikazioa[]  $Planifikazioa                             
 *  
 * @method Ohartaraztea                           getOhartaraztea()                          
 * @method Doctrine_Collection|Gertakaria[]       getGertakaria()                            
 * @method Doctrine_Collection|Fitxategia[]       getFitxategia()                            
 * @method Doctrine_Collection|Iruzkina[]         getIruzkina()                              
 * @method Doctrine_Collection|Planifikazioa[]    getPlanifikazioa()                         
 *  
 * @method Langilea                               setOhartaraztea(Ohartaraztea $val)         
 * @method Langilea                               setGertakaria(Doctrine_Collection $val)    
 * @method Langilea                               setFitxategia(Doctrine_Collection $val)    
 * @method Langilea                               setIruzkina(Doctrine_Collection $val)      
 * @method Langilea                               setPlanifikazioa(Doctrine_Collection $val) 
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLangilea extends sfGuardUser
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ohartaraztea', array(
             'local' => 'ohartaraztea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'langilea_id'));

        $this->hasMany('Fitxategia', array(
             'local' => 'id',
             'foreign' => 'langilea_id'));

        $this->hasMany('Iruzkina', array(
             'local' => 'id',
             'foreign' => 'langilea_id'));

        $this->hasMany('Planifikazioa', array(
             'local' => 'id',
             'foreign' => 'langilea_id'));
    }
}