<?php

/**
 * BaseKalea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $barrutia_id
 * @property integer $auzoa_id
 * @property string $izena
 * @property string $google
 * @property Barrutia $Barrutia
 * @property Auzoa $Auzoa
 * @property Doctrine_Collection $Gertakaria
 * 
 * @method integer             getBarrutiaId()  Returns the current record's "barrutia_id" value
 * @method integer             getAuzoaId()     Returns the current record's "auzoa_id" value
 * @method string              getIzena()       Returns the current record's "izena" value
 * @method string              getGoogle()      Returns the current record's "google" value
 * @method Barrutia            getBarrutia()    Returns the current record's "Barrutia" value
 * @method Auzoa               getAuzoa()       Returns the current record's "Auzoa" value
 * @method Doctrine_Collection getGertakaria()  Returns the current record's "Gertakaria" collection
 * @method Kalea               setBarrutiaId()  Sets the current record's "barrutia_id" value
 * @method Kalea               setAuzoaId()     Sets the current record's "auzoa_id" value
 * @method Kalea               setIzena()       Sets the current record's "izena" value
 * @method Kalea               setGoogle()      Sets the current record's "google" value
 * @method Kalea               setBarrutia()    Sets the current record's "Barrutia" value
 * @method Kalea               setAuzoa()       Sets the current record's "Auzoa" value
 * @method Kalea               setGertakaria()  Sets the current record's "Gertakaria" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKalea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kalea');
        $this->hasColumn('barrutia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('auzoa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('google', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Barrutia', array(
             'local' => 'barrutia_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Auzoa', array(
             'local' => 'auzoa_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'kalea_id'));
    }
}