<?php

/**
 * BaseFitxategia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gertakaria_id
 * @property integer $langilea_id
 * @property string $fitxategia
 * @property string $deskribapena
 * @property Gertakaria $Gertakaria
 * @property Langilea $Langilea
 * 
 * @method integer    getGertakariaId()  Returns the current record's "gertakaria_id" value
 * @method integer    getLangileaId()    Returns the current record's "langilea_id" value
 * @method string     getFitxategia()    Returns the current record's "fitxategia" value
 * @method string     getDeskribapena()  Returns the current record's "deskribapena" value
 * @method Gertakaria getGertakaria()    Returns the current record's "Gertakaria" value
 * @method Langilea   getLangilea()      Returns the current record's "Langilea" value
 * @method Fitxategia setGertakariaId()  Sets the current record's "gertakaria_id" value
 * @method Fitxategia setLangileaId()    Sets the current record's "langilea_id" value
 * @method Fitxategia setFitxategia()    Sets the current record's "fitxategia" value
 * @method Fitxategia setDeskribapena()  Sets the current record's "deskribapena" value
 * @method Fitxategia setGertakaria()    Sets the current record's "Gertakaria" value
 * @method Fitxategia setLangilea()      Sets the current record's "Langilea" value
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFitxategia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fitxategia');
        $this->hasColumn('gertakaria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('langilea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('fitxategia', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('deskribapena', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gertakaria', array(
             'local' => 'gertakaria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Langilea', array(
             'local' => 'langilea_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}