<?php

/**
 * BaseEgoera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $izena
 * @property string $kolorea
 * @property Doctrine_Collection $Gertakaria
 * 
 * @method string              getIzena()      Returns the current record's "izena" value
 * @method string              getKolorea()    Returns the current record's "kolorea" value
 * @method Doctrine_Collection getGertakaria() Returns the current record's "Gertakaria" collection
 * @method Egoera              setIzena()      Sets the current record's "izena" value
 * @method Egoera              setKolorea()    Sets the current record's "kolorea" value
 * @method Egoera              setGertakaria() Sets the current record's "Gertakaria" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEgoera extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('egoera');
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('kolorea', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'egoera_id'));
    }
}