<?php

/**
 * BaseEraikina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                            $izena                                  Type: string(255)
 * @property int                               $barrutia_id                            Type: integer
 * @property int                               $auzoa_id                               Type: integer
 * @property double                            $longitudea                             Type: double(18)
 * @property double                            $latitudea                              Type: double(18)
 * @property Barrutia                          $Barrutia                               
 * @property Auzoa                             $Auzoa                                  
 * @property Doctrine_Collection|Gertakaria[]  $Gertakaria                             
 *  
 * @method string                              getIzena()                              Type: string(255)
 * @method int                                 getBarrutiaId()                         Type: integer
 * @method int                                 getAuzoaId()                            Type: integer
 * @method double                              getLongitudea()                         Type: double(18)
 * @method double                              getLatitudea()                          Type: double(18)
 * @method Barrutia                            getBarrutia()                           
 * @method Auzoa                               getAuzoa()                              
 * @method Doctrine_Collection|Gertakaria[]    getGertakaria()                         
 *  
 * @method Eraikina                            setIzena(string $val)                   Type: string(255)
 * @method Eraikina                            setBarrutiaId(int $val)                 Type: integer
 * @method Eraikina                            setAuzoaId(int $val)                    Type: integer
 * @method Eraikina                            setLongitudea(double $val)              Type: double(18)
 * @method Eraikina                            setLatitudea(double $val)               Type: double(18)
 * @method Eraikina                            setBarrutia(Barrutia $val)              
 * @method Eraikina                            setAuzoa(Auzoa $val)                    
 * @method Eraikina                            setGertakaria(Doctrine_Collection $val) 
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEraikina extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eraikina');
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('barrutia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('auzoa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('longitudea', 'double', 18, array(
             'type' => 'double',
             'scale' => 6,
             'notnull' => true,
             'length' => 18,
             ));
        $this->hasColumn('latitudea', 'double', 18, array(
             'type' => 'double',
             'scale' => 6,
             'notnull' => true,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Barrutia', array(
             'local' => 'barrutia_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Auzoa', array(
             'local' => 'auzoa_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'eraikina_id'));
    }
}