<?php

/**
 * BaseAuzoa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                               $barrutia_id                            Type: integer
 * @property string                            $izena                                  Type: string(255), unique
 * @property Barrutia                          $Barrutia                               
 * @property Doctrine_Collection|Gertakaria[]  $Gertakaria                             
 * @property Doctrine_Collection|Kalea[]       $Kalea                                  
 * @property Doctrine_Collection|Eraikina[]    $Eraikina                               
 *  
 * @method int                                 getBarrutiaId()                         Type: integer
 * @method string                              getIzena()                              Type: string(255), unique
 * @method Barrutia                            getBarrutia()                           
 * @method Doctrine_Collection|Gertakaria[]    getGertakaria()                         
 * @method Doctrine_Collection|Kalea[]         getKalea()                              
 * @method Doctrine_Collection|Eraikina[]      getEraikina()                           
 *  
 * @method Auzoa                               setBarrutiaId(int $val)                 Type: integer
 * @method Auzoa                               setIzena(string $val)                   Type: string(255), unique
 * @method Auzoa                               setBarrutia(Barrutia $val)              
 * @method Auzoa                               setGertakaria(Doctrine_Collection $val) 
 * @method Auzoa                               setKalea(Doctrine_Collection $val)      
 * @method Auzoa                               setEraikina(Doctrine_Collection $val)   
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuzoa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('auzoa');
        $this->hasColumn('barrutia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Barrutia', array(
             'local' => 'barrutia_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'auzoa_id'));

        $this->hasMany('Kalea', array(
             'local' => 'id',
             'foreign' => 'auzoa_id'));

        $this->hasMany('Eraikina', array(
             'local' => 'id',
             'foreign' => 'auzoa_id'));
    }
}