<?php

/**
 * BaseKontaktuaOhartaraztea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                              $ordena                                Type: integer
 * @property string                           $modua                                 Type: string(100)
 * @property Doctrine_Collection|Kontaktua[]  $Kontaktua                             
 *  
 * @method int                                getOrdena()                            Type: integer
 * @method string                             getModua()                             Type: string(100)
 * @method Doctrine_Collection|Kontaktua[]    getKontaktua()                         
 *  
 * @method KontaktuaOhartaraztea              setOrdena(int $val)                    Type: integer
 * @method KontaktuaOhartaraztea              setModua(string $val)                  Type: string(100)
 * @method KontaktuaOhartaraztea              setKontaktua(Doctrine_Collection $val) 
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKontaktuaOhartaraztea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kontaktua_ohartaraztea');
        $this->hasColumn('ordena', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('modua', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Kontaktua', array(
             'local' => 'id',
             'foreign' => 'ohartarazi'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'modua',
             ),
             ));
        $this->actAs($i18n0);
    }
}