<?php

/**
 * BaseKontaktua
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                 $izena                                               Type: string(255)
 * @property string                 $abizenak                                            Type: string(255)
 * @property string                 $nan                                                 Type: string(9)
 * @property string                 $posta                                               Type: string(100)
 * @property string                 $telefonoa                                           Type: string(30)
 * @property int                    $ohartarazi                                          Type: integer
 * @property string                 $hizkuntza                                           Type: string(2)
 * @property string                 $pasahitza                                           Type: string(255)
 * @property KontaktuaOhartaraztea  $KontaktuaOhartaraztea                               
 * @property Gertakaria             $Gertakaria                                          
 *  
 * @method string                   getIzena()                                           Type: string(255)
 * @method string                   getAbizenak()                                        Type: string(255)
 * @method string                   getNan()                                             Type: string(9)
 * @method string                   getPosta()                                           Type: string(100)
 * @method string                   getTelefonoa()                                       Type: string(30)
 * @method int                      getOhartarazi()                                      Type: integer
 * @method string                   getHizkuntza()                                       Type: string(2)
 * @method string                   getPasahitza()                                       Type: string(255)
 * @method KontaktuaOhartaraztea    getKontaktuaOhartaraztea()                           
 * @method Gertakaria               getGertakaria()                                      
 *  
 * @method Kontaktua                setIzena(string $val)                                Type: string(255)
 * @method Kontaktua                setAbizenak(string $val)                             Type: string(255)
 * @method Kontaktua                setNan(string $val)                                  Type: string(9)
 * @method Kontaktua                setPosta(string $val)                                Type: string(100)
 * @method Kontaktua                setTelefonoa(string $val)                            Type: string(30)
 * @method Kontaktua                setOhartarazi(int $val)                              Type: integer
 * @method Kontaktua                setHizkuntza(string $val)                            Type: string(2)
 * @method Kontaktua                setPasahitza(string $val)                            Type: string(255)
 * @method Kontaktua                setKontaktuaOhartaraztea(KontaktuaOhartaraztea $val) 
 * @method Kontaktua                setGertakaria(Gertakaria $val)                       
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKontaktua extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kontaktua');
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('abizenak', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('nan', 'string', 9, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 9,
             ));
        $this->hasColumn('posta', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('telefonoa', 'string', 30, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 30,
             ));
        $this->hasColumn('ohartarazi', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('hizkuntza', 'string', 2, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('pasahitza', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('KontaktuaOhartaraztea', array(
             'local' => 'ohartarazi',
             'foreign' => 'id'));

        $this->hasOne('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'kontaktua_id'));
    }
}