<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Saila', 'doctrine');

/**
 * BaseSaila
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection|Gertakaria[]  $Gertakaria                             
 * @property Doctrine_Collection|SailaMota[]   $SailaMota                              
 *  
 * @method Doctrine_Collection|Gertakaria[]    getGertakaria()                         
 * @method Doctrine_Collection|SailaMota[]     getSailaMota()                          
 *  
 * @method Saila                               setGertakaria(Doctrine_Collection $val) 
 * @method Saila                               setSailaMota(Doctrine_Collection $val)  
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSaila extends sfGuardGroup
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'saila_id'));

        $this->hasMany('SailaMota', array(
             'local' => 'id',
             'foreign' => 'saila_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($i18n0);
    }
}