<?php

/**
 * BaseErlazioak
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hasiera_id
 * @property integer $amaiera_id
 * @property integer $erlazio_mota_id
 * @property ErlazioMota $ErlazioMota
 * @property Gertakaria $Gertakaria
 * @property Gertakaria $Gertakaria_3
 * 
 * @method integer     getHasieraId()       Returns the current record's "hasiera_id" value
 * @method integer     getAmaieraId()       Returns the current record's "amaiera_id" value
 * @method integer     getErlazioMotaId()   Returns the current record's "erlazio_mota_id" value
 * @method ErlazioMota getErlazioMota()     Returns the current record's "ErlazioMota" value
 * @method Gertakaria  getGertakaria()      Returns the current record's "Gertakaria" value
 * @method Gertakaria  getGertakaria3()     Returns the current record's "Gertakaria_3" value
 * @method Erlazioak   setHasieraId()       Sets the current record's "hasiera_id" value
 * @method Erlazioak   setAmaieraId()       Sets the current record's "amaiera_id" value
 * @method Erlazioak   setErlazioMotaId()   Sets the current record's "erlazio_mota_id" value
 * @method Erlazioak   setErlazioMota()     Sets the current record's "ErlazioMota" value
 * @method Erlazioak   setGertakaria()      Sets the current record's "Gertakaria" value
 * @method Erlazioak   setGertakaria3()     Sets the current record's "Gertakaria_3" value
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseErlazioak extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('erlazioak');
        $this->hasColumn('hasiera_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('amaiera_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('erlazio_mota_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ErlazioMota', array(
             'local' => 'erlazio_mota_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Gertakaria', array(
             'local' => 'amaiera_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Gertakaria as Gertakaria_3', array(
             'local' => 'hasiera_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}