<?php

/**
 * BasePlanifikazioa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gertakaria_id
 * @property integer $langilea_id
 * @property date $hasiera_data
 * @property time $hasiera_ordua_noiztik
 * @property time $hasiera_ordua_noizarte
 * @property date $amaiera_data
 * @property time $amaiera_ordua_noiztik
 * @property time $amaiera_ordua_noizarte
 * @property Gertakaria $Gertakaria
 * @property Langilea $Langilea
 * 
 * @method integer       getGertakariaId()           Returns the current record's "gertakaria_id" value
 * @method integer       getLangileaId()             Returns the current record's "langilea_id" value
 * @method date          getHasieraData()            Returns the current record's "hasiera_data" value
 * @method time          getHasieraOrduaNoiztik()    Returns the current record's "hasiera_ordua_noiztik" value
 * @method time          getHasieraOrduaNoizarte()   Returns the current record's "hasiera_ordua_noizarte" value
 * @method date          getAmaieraData()            Returns the current record's "amaiera_data" value
 * @method time          getAmaieraOrduaNoiztik()    Returns the current record's "amaiera_ordua_noiztik" value
 * @method time          getAmaieraOrduaNoizarte()   Returns the current record's "amaiera_ordua_noizarte" value
 * @method Gertakaria    getGertakaria()             Returns the current record's "Gertakaria" value
 * @method Langilea      getLangilea()               Returns the current record's "Langilea" value
 * @method Planifikazioa setGertakariaId()           Sets the current record's "gertakaria_id" value
 * @method Planifikazioa setLangileaId()             Sets the current record's "langilea_id" value
 * @method Planifikazioa setHasieraData()            Sets the current record's "hasiera_data" value
 * @method Planifikazioa setHasieraOrduaNoiztik()    Sets the current record's "hasiera_ordua_noiztik" value
 * @method Planifikazioa setHasieraOrduaNoizarte()   Sets the current record's "hasiera_ordua_noizarte" value
 * @method Planifikazioa setAmaieraData()            Sets the current record's "amaiera_data" value
 * @method Planifikazioa setAmaieraOrduaNoiztik()    Sets the current record's "amaiera_ordua_noiztik" value
 * @method Planifikazioa setAmaieraOrduaNoizarte()   Sets the current record's "amaiera_ordua_noizarte" value
 * @method Planifikazioa setGertakaria()             Sets the current record's "Gertakaria" value
 * @method Planifikazioa setLangilea()               Sets the current record's "Langilea" value
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlanifikazioa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('planifikazioa');
        $this->hasColumn('gertakaria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('langilea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('hasiera_data', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hasiera_ordua_noiztik', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('hasiera_ordua_noizarte', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('amaiera_data', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('amaiera_ordua_noiztik', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('amaiera_ordua_noizarte', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gertakaria', array(
             'local' => 'gertakaria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Langilea', array(
             'local' => 'langilea_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}