<?php

/**
 * BaseEraikina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $izena
 * @property integer $barrutia_id
 * @property integer $auzoa_id
 * @property double $longitudea
 * @property double $latitudea
 * @property Barrutia $Barrutia
 * @property Auzoa $Auzoa
 * @property Doctrine_Collection $Gertakaria
 * 
 * @method string              getIzena()       Returns the current record's "izena" value
 * @method integer             getBarrutiaId()  Returns the current record's "barrutia_id" value
 * @method integer             getAuzoaId()     Returns the current record's "auzoa_id" value
 * @method double              getLongitudea()  Returns the current record's "longitudea" value
 * @method double              getLatitudea()   Returns the current record's "latitudea" value
 * @method Barrutia            getBarrutia()    Returns the current record's "Barrutia" value
 * @method Auzoa               getAuzoa()       Returns the current record's "Auzoa" value
 * @method Doctrine_Collection getGertakaria()  Returns the current record's "Gertakaria" collection
 * @method Eraikina            setIzena()       Sets the current record's "izena" value
 * @method Eraikina            setBarrutiaId()  Sets the current record's "barrutia_id" value
 * @method Eraikina            setAuzoaId()     Sets the current record's "auzoa_id" value
 * @method Eraikina            setLongitudea()  Sets the current record's "longitudea" value
 * @method Eraikina            setLatitudea()   Sets the current record's "latitudea" value
 * @method Eraikina            setBarrutia()    Sets the current record's "Barrutia" value
 * @method Eraikina            setAuzoa()       Sets the current record's "Auzoa" value
 * @method Eraikina            setGertakaria()  Sets the current record's "Gertakaria" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEraikina extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eraikina');
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('barrutia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('auzoa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('longitudea', 'double', 18, array(
             'type' => 'double',
             'scale' => 6,
             'notnull' => true,
             'length' => 18,
             ));
        $this->hasColumn('latitudea', 'double', 18, array(
             'type' => 'double',
             'scale' => 6,
             'notnull' => true,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Barrutia', array(
             'local' => 'barrutia_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Auzoa', array(
             'local' => 'auzoa_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'eraikina_id'));
    }
}