<?php

/**
 * BaseEgunTarteak
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $minimoa             Type: integer, unique
 * @property int          $maximoa             Type: integer, unique
 *  
 * @method int            getMinimoa()         Type: integer, unique
 * @method int            getMaximoa()         Type: integer, unique
 *  
 * @method EgunTarteak    setMinimoa(int $val) Type: integer, unique
 * @method EgunTarteak    setMaximoa(int $val) Type: integer, unique
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEgunTarteak extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('egun_tarteak');
        $this->hasColumn('minimoa', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('maximoa', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}