<?php

/**
 * BaseIruzkina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int         $gertakaria_id                 Type: integer
 * @property int         $langilea_id                   Type: integer
 * @property int         $ekintza_id                    Type: integer
 * @property string      $testua                        Type: string(4000)
 * @property bool        $publikoa                      Type: boolean
 * @property Gertakaria  $Gertakaria                    
 * @property Langilea    $Langilea                      
 * @property Ekintza     $Ekintza                       
 *  
 * @method int           getGertakariaId()              Type: integer
 * @method int           getLangileaId()                Type: integer
 * @method int           getEkintzaId()                 Type: integer
 * @method string        getTestua()                    Type: string(4000)
 * @method bool          getPublikoa()                  Type: boolean
 * @method Gertakaria    getGertakaria()                
 * @method Langilea      getLangilea()                  
 * @method Ekintza       getEkintza()                   
 *  
 * @method Iruzkina      setGertakariaId(int $val)      Type: integer
 * @method Iruzkina      setLangileaId(int $val)        Type: integer
 * @method Iruzkina      setEkintzaId(int $val)         Type: integer
 * @method Iruzkina      setTestua(string $val)         Type: string(4000)
 * @method Iruzkina      setPublikoa(bool $val)         Type: boolean
 * @method Iruzkina      setGertakaria(Gertakaria $val) 
 * @method Iruzkina      setLangilea(Langilea $val)     
 * @method Iruzkina      setEkintza(Ekintza $val)       
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIruzkina extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('iruzkina');
        $this->hasColumn('gertakaria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('langilea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('ekintza_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('testua', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('publikoa', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gertakaria', array(
             'local' => 'gertakaria_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Langilea', array(
             'local' => 'langilea_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Ekintza', array(
             'local' => 'ekintza_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}