<?php

/**
 * BaseSailaMota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int        $saila_id            Type: integer
 * @property int        $mota_id             Type: integer
 * @property Saila      $Saila               
 * @property Mota       $Mota                
 *  
 * @method int          getSailaId()         Type: integer
 * @method int          getMotaId()          Type: integer
 * @method Saila        getSaila()           
 * @method Mota         getMota()            
 *  
 * @method SailaMota    setSailaId(int $val) Type: integer
 * @method SailaMota    setMotaId(int $val)  Type: integer
 * @method SailaMota    setSaila(Saila $val) 
 * @method SailaMota    setMota(Mota $val)   
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSailaMota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('saila_mota');
        $this->hasColumn('saila_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mota_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Saila', array(
             'local' => 'saila_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Mota', array(
             'local' => 'mota_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}