<?php

/**
 * BaseAzpimota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                               $mota_id                                Type: integer
 * @property string                            $izena                                  Type: string(255)
 * @property Mota                              $Mota                                   
 * @property Doctrine_Collection|Gertakaria[]  $Gertakaria                             
 *  
 * @method int                                 getMotaId()                             Type: integer
 * @method string                              getIzena()                              Type: string(255)
 * @method Mota                                getMota()                               
 * @method Doctrine_Collection|Gertakaria[]    getGertakaria()                         
 *  
 * @method Azpimota                            setMotaId(int $val)                     Type: integer
 * @method Azpimota                            setIzena(string $val)                   Type: string(255)
 * @method Azpimota                            setMota(Mota $val)                      
 * @method Azpimota                            setGertakaria(Doctrine_Collection $val) 
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAzpimota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('azpimota');
        $this->hasColumn('mota_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mota', array(
             'local' => 'mota_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'azpimota_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'izena',
             ),
             ));
        $this->actAs($i18n0);
    }
}