<?php

/**
 * BaseKalea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                               $barrutia_id                            Type: integer
 * @property int                               $auzoa_id                               Type: integer
 * @property string                            $izena                                  Type: string(255), unique
 * @property string                            $google                                 Type: string(255)
 * @property Barrutia                          $Barrutia                               
 * @property Auzoa                             $Auzoa                                  
 * @property Doctrine_Collection|Gertakaria[]  $Gertakaria                             
 *  
 * @method int                                 getBarrutiaId()                         Type: integer
 * @method int                                 getAuzoaId()                            Type: integer
 * @method string                              getIzena()                              Type: string(255), unique
 * @method string                              getGoogle()                             Type: string(255)
 * @method Barrutia                            getBarrutia()                           
 * @method Auzoa                               getAuzoa()                              
 * @method Doctrine_Collection|Gertakaria[]    getGertakaria()                         
 *  
 * @method Kalea                               setBarrutiaId(int $val)                 Type: integer
 * @method Kalea                               setAuzoaId(int $val)                    Type: integer
 * @method Kalea                               setIzena(string $val)                   Type: string(255), unique
 * @method Kalea                               setGoogle(string $val)                  Type: string(255)
 * @method Kalea                               setBarrutia(Barrutia $val)              
 * @method Kalea                               setAuzoa(Auzoa $val)                    
 * @method Kalea                               setGertakaria(Doctrine_Collection $val) 
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKalea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kalea');
        $this->hasColumn('barrutia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('auzoa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('google', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Barrutia', array(
             'local' => 'barrutia_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Auzoa', array(
             'local' => 'auzoa_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'kalea_id'));
    }
}