<?php

/**
 * BaseIruzkina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gertakaria_id
 * @property integer $langilea_id
 * @property integer $ekintza_id
 * @property string $testua
 * @property Gertakaria $Gertakaria
 * @property Langilea $Langilea
 * @property Ekintza $Ekintza
 * 
 * @method integer    getGertakariaId()  Returns the current record's "gertakaria_id" value
 * @method integer    getLangileaId()    Returns the current record's "langilea_id" value
 * @method integer    getEkintzaId()     Returns the current record's "ekintza_id" value
 * @method string     getTestua()        Returns the current record's "testua" value
 * @method Gertakaria getGertakaria()    Returns the current record's "Gertakaria" value
 * @method Langilea   getLangilea()      Returns the current record's "Langilea" value
 * @method Ekintza    getEkintza()       Returns the current record's "Ekintza" value
 * @method Iruzkina   setGertakariaId()  Sets the current record's "gertakaria_id" value
 * @method Iruzkina   setLangileaId()    Sets the current record's "langilea_id" value
 * @method Iruzkina   setEkintzaId()     Sets the current record's "ekintza_id" value
 * @method Iruzkina   setTestua()        Sets the current record's "testua" value
 * @method Iruzkina   setGertakaria()    Sets the current record's "Gertakaria" value
 * @method Iruzkina   setLangilea()      Sets the current record's "Langilea" value
 * @method Iruzkina   setEkintza()       Sets the current record's "Ekintza" value
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIruzkina extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('iruzkina');
        $this->hasColumn('gertakaria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('langilea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('ekintza_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('testua', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gertakaria', array(
             'local' => 'gertakaria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Langilea', array(
             'local' => 'langilea_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Ekintza', array(
             'local' => 'ekintza_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}