<?php

/**
 * BaseBarrutia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                            $izena                                  Type: string(255), unique
 * @property Doctrine_Collection|Gertakaria[]  $Gertakaria                             
 * @property Doctrine_Collection|Auzoa[]       $Auzoa                                  
 * @property Doctrine_Collection|Kalea[]       $Kalea                                  
 * @property Doctrine_Collection|Eraikina[]    $Eraikina                               
 *  
 * @method string                              getIzena()                              Type: string(255), unique
 * @method Doctrine_Collection|Gertakaria[]    getGertakaria()                         
 * @method Doctrine_Collection|Auzoa[]         getAuzoa()                              
 * @method Doctrine_Collection|Kalea[]         getKalea()                              
 * @method Doctrine_Collection|Eraikina[]      getEraikina()                           
 *  
 * @method Barrutia                            setIzena(string $val)                   Type: string(255), unique
 * @method Barrutia                            setGertakaria(Doctrine_Collection $val) 
 * @method Barrutia                            setAuzoa(Doctrine_Collection $val)      
 * @method Barrutia                            setKalea(Doctrine_Collection $val)      
 * @method Barrutia                            setEraikina(Doctrine_Collection $val)   
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBarrutia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('barrutia');
        $this->hasColumn('izena', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Gertakaria', array(
             'local' => 'id',
             'foreign' => 'barrutia_id'));

        $this->hasMany('Auzoa', array(
             'local' => 'id',
             'foreign' => 'barrutia_id'));

        $this->hasMany('Kalea', array(
             'local' => 'id',
             'foreign' => 'barrutia_id'));

        $this->hasMany('Eraikina', array(
             'local' => 'id',
             'foreign' => 'barrutia_id'));
    }
}