<?php

/**
 * BaseEgunTarteak
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $minimoa
 * @property integer $maximoa
 * 
 * @method integer     getMinimoa() Returns the current record's "minimoa" value
 * @method integer     getMaximoa() Returns the current record's "maximoa" value
 * @method EgunTarteak setMinimoa() Sets the current record's "minimoa" value
 * @method EgunTarteak setMaximoa() Sets the current record's "maximoa" value
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEgunTarteak extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('egun_tarteak');
        $this->hasColumn('minimoa', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('maximoa', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}