<?php

/**
 * BaseEkintza
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $mota
 * @property Doctrine_Collection $Iruzkina
 * 
 * @method string              getMota()     Returns the current record's "mota" value
 * @method Doctrine_Collection getIruzkina() Returns the current record's "Iruzkina" collection
 * @method Ekintza             setMota()     Sets the current record's "mota" value
 * @method Ekintza             setIruzkina() Sets the current record's "Iruzkina" collection
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEkintza extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ekintza');
        $this->hasColumn('mota', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Iruzkina', array(
             'local' => 'id',
             'foreign' => 'ekintza_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'mota',
             ),
             ));
        $this->actAs($i18n0);
    }
}