<?php

/**
 * Arloa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Arloa extends BaseArloa
{
	public function __toString()
	{
		// Fix PHP 7
		if ($this->getTable()->hasRelation('Translation'))
			$this->loadReference('Translation');

		if (!is_null($this->getId()))
			return $this->getIzena();
		else
			return '';
	}
}
