<?php

/**
 * ArloaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArloaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ArloaTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Arloa');
    }
}