<?php

/**
 * EgunTarteakTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EgunTarteakTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object EgunTarteakTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('EgunTarteak');
	}
}