<?php

/**
 * Ekintza
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gerkud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ekintza extends BaseEkintza
{
	public function __toString()
	{
		// Fix PHP 7
		if ($this->getTable()->hasRelation('Translation'))
			$this->loadReference('Translation');

		return $this->getMota();
	}
}
