<?php

/**
 * Eraikina
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Eraikina extends BaseEraikina
{
	public function __toString()
	{
		return $this->getIzena();
	}
}
