<?php

/**
 * Iruzkina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gerkud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Iruzkina extends BaseIruzkina
{

  public function getGertakaria()
  {
	  $q = Doctrine_Query::create()
	    ->from('Gertakaria g')
	    ->where('g.id = ?', $this->getGertakariaId());
	    return $q->execute();
  }

  public function getSaila($sailaId)
  {
          $q = Doctrine_Query::create()
            ->from('Saila s')
            ->where('s.id = ?', $sailaId);
            return $q->execute();
	  

  }

  public function save(Doctrine_Connection $conn = null)
  {
	//  $conn = $conn ? $conn : GertakariaTable::getConnection();
	$conn = $conn ? $conn : Doctrine_Core::getTable('Iruzkina')->getConnection();
	$conn->beginTransaction();
	try
	{
	        $ret = parent::save($conn);
//		$iruzkina = $this->getIruzkina();
//		echo "<script>alert('Iruzkina gordetzen ari da.....')</script>";
	        $conn->commit();

		$gertakariak = $this->getGertakaria();
		$erab = Doctrine::getTable('langilea')->find(array($gertakariak[0]->getLangileaId()));
                $nork = Doctrine::getTable('langilea')->find(array($this->getLangileaId()))->getName();

		if ($erab->getOhartarazteaId()!=1)
		{
			$mailer = sfContext::getInstance()->getMailer();
                        $mezua = Swift_Message::newInstance();
                        $mezua->setFrom(sfConfig::get('app_abisuak_nork'));
                        $mezua->setTo($erab->getEmailAddress());
			$cid = $mezua->embed(Swift_Image::fromPath('./images/Gerkud-txiki.jpg'));

//			echo 'case-a baino lehen';
			switch ($this->getEkintzaId())
			{
			case 1: //Iruzkina
                                if ($erab->getOhartarazteaId()==3)
				{
/*
					$mezua->setSubject($this->getEkintza().' '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
        		                $mezua->setBody($this->getTestua());
					$mailer->send($mezua);
*/
                                        $mezua->setSubject($this->getEkintza().' '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
                                        $html='<table border=0><tr><td colspan=2><img src="'.$cid.'" /></td></tr>'
                                        .'<tr><th colspan=2><hr><br></th></tr>'
                                        .'<tr><th align=left><b>Gertakariaren kodea:</b></th><td>'.$gertakariak[0]->getId().'</td></tr>'
                                        .'<tr><th colspan=2 align=left><b>Gertakariaren deskribapena:</b></th></tr><tr><td colspan=2>'
                                        .$gertakariak[0]->getDeskribapena().'</td></tr>'
                                        .'</table>'
                                        .'<br>'
                                        .'<p>Zuk zabaldutako gertakari honek ondorengo aldaketa izan du:</p>'
                                        .'<table border=0>'
                                        .'<tr><th align=left><b>Iruzkina:</b></th><td>'.$this->getTestua().'</td></tr>'
                                        .'<tr><th align=left><b>Nork egin du:</b></th><td>'.$this->getLangilea()->getName().'</td></tr>'
                                        .'</table>'
                                        .'<br><br>'
                                        .'<hr><p>EZ ERANTZUN MEZU HONI. Mezu hau automatikoki bidali dizu GERKUD gertakarien kudeaketa aplikazioak zuk horrela konfiguratuta daukazulako. Ez baduzu horrelako mezurik jaso nahi, aldatu konfigurazioa "nire datuak" atalean</p>';
                                        $mezua->setBody($html);
                                        $mezua->setContentType('text/html');
                                        $mailer->send($mezua);
				}		
				break;

			case 2: //Esleipena
                                if (($erab->getOhartarazteaId()==3)&&($this->getTestua()!=''))
                                {
//                              echo '<script>alert("esleipena hasieran")</script>';
                                        $mezua->setSubject($this->getEkintza().' '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
                                        $html='<table border=0><tr><td colspan=2><img src="'.$cid.'" /></td></tr>'
                                        .'<tr><th colspan=2><hr><br></th></tr>'
                                        .'<tr><th align=left><b>Gertakariaren kodea:</b></th><td>'.$gertakariak[0]->getId().'</td></tr>'
                                        .'<tr><th colspan=2 align=left><b>Gertakariaren deskribapena:</b></th></tr><tr><td colspan=2>'
                                        .$gertakariak[0]->getDeskribapena().'</td></tr>'
                                        .'</table>'
                                        .'<br>'
                                        .'<p>Zuk zabaldutako gertakari honek ondorengo aldaketa izan du:</p>'
                                        .'<table border=0>'
                                        .'<tr><th align=left><b>Aldaketa:</b></th><td>'.$this->getTestua().'</td></tr>'
                                        .'<tr><th align=left><b>Nork egin du:</b></th><td>'.$this->getLangilea()->getName().'</td></tr>'
                                        .'</table>'
                                        .'<br><br>'
                                        .'<hr><p>EZ ERANTZUN MEZU HONI. Mezu hau automatikoki bidali dizu GERKUD gertakarien kudeaketa aplikazioak zuk horrela konfiguratuta daukazulako. Ez baduzu horrelako mezurik jaso nahi, aldatu konfigurazioa "nire datuak" atalean</p>';
                                        $mezua->setBody($html);
                                        $mezua->setContentType('text/html');
                                        $mailer->send($mezua);
//                              echo '<script>alert("Esleipena amaiera")</script>';
                                }
                                break;

			case 3: //Berrirekitzea
                                if ($erab->getOhartarazteaId()==3)
                                {
/*
                                        $mezua->setSubject($this->getEkintza().' '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
                                        $mezua->setBody($nork.'-(e)k '.$gertakariak[0]->getId()
	                                        . ' kodea duen gertakaria berrireki du:\n'
        	                                .$this->getTestua());
                                        $mailer->send($mezua);
*/

                                        $mezua->setSubject($this->getEkintza().' '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
	                                $html='<table border=0><tr><td colspan=2><img src="'.$cid.'" /></td></tr>'
        	                        .'<tr><th colspan=2><hr><br></th></tr>'
                	                .'<tr><th align=left><b>Gertakariaren kodea:</b></th><td>'.$gertakariak[0]->getId().'</td></tr>'
                        	        .'<tr><th colspan=2 align=left><b>Gertakariaren deskribapena:</b></th></tr><tr><td colspan=2>'
	                                .$gertakariak[0]->getDeskribapena().'</td></tr>'
	                                .'</table>'
	                                .'<br>'
	                                .'<p>Zuk zabaldutako gertakari honek ondorengo aldaketa izan du:</p>'
	                                .'<table border=0>'
	                                .'<tr><th align=left><b>Aldaketa:</b></th><td>Berrireki da'.'</td></tr>'
	                                .'<tr><th align=left><b>Nork egin du:</b></th><td>'.$this->getLangilea()->getName().'</td></tr>'
	                                .'</table>'
	                                .'<br><br>'
	                                .'<hr><p>EZ ERANTZUN MEZU HONI. Mezu hau automatikoki bidali dizu GERKUD gertakarien kudeaketa aplikazioak zuk horrela konfiguratuta daukazulako. Ez baduzu horrelako mezurik jaso nahi, aldatu konfigurazioa "nire datuak" atalean</p>';
        	                        $mezua->setBody($html);
	                                $mezua->setContentType('text/html');
	                                $mailer->send($mezua);
                                }
                                break;

			case 4: //Fitxategia
                                if ($erab->getOhartarazteaId()==3)
                                {
/*
                                        $mezua->setSubject($this->getEkintza().' '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
                                        $mezua->setBody($nork.'-(e)k '.$gertakariak[0]->getId()
					. ' kodea duen gertakariari fitxategi berria gehitu dio:\n '
                                        .$this->getTestua());
                                        $mailer->send($mezua);
*/

                                        $mezua->setSubject($this->getEkintza().' '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
                                	$html='<table border=0><tr><td colspan=2><img src="'.$cid.'" /></td></tr>'
	                                .'<tr><th colspan=2><hr><br></th></tr>'
        	                        .'<tr><th align=left><b>Gertakariaren kodea:</b></th><td>'.$gertakariak[0]->getId().'</td></tr>'
                	                .'<tr><th colspan=2 align=left><b>Gertakariaren deskribapena:</b></th></tr><tr><td colspan=2>'
	                                .$gertakariak[0]->getDeskribapena().'</td></tr>'
	                                .'</table>'
	                                .'<br>'
	                                .'<p>Zuk zabaldutako gertakari honek ondorengo aldaketa izan du:</p>'
	                                .'<table border=0>'
	                                .'<tr><th align=left><b>Aldaketa:</b></th><td>'.$this->getTestua().'</td></tr>'
	                                .'<tr><th align=left><b>Nork egin du:</b></th><td>'.$this->getLangilea()->getName().'</td></tr>'
	                                .'</table>'
	                                .'<br><br>'
	                                .'<hr><p>EZ ERANTZUN MEZU HONI. Mezu hau automatikoki bidali dizu GERKUD gertakarien kudeaketa aplikazioak zuk horrela konfiguratuta daukazulako. Ez baduzu horrelako mezurik jaso nahi, aldatu konfigurazioa "nire datuak" atalean</p>';
	                                $mezua->setBody($html);
	                                $mezua->setContentType('text/html');
	                                $mailer->send($mezua);
                                }
                                break;

			case 5: //Egoera aldatzea
/*
                                $mezua->setSubject($gertakariak[0]->getEgoera().' '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
                                $mezua->setBody($nork.'-(e)k '.$gertakariak[0]->getId()
                                . ' kodea duen gertakaria '.$gertakariak[0]->getEgoera().' egoeran jarri du.');
				$mailer->send($mezua);
				break;
*/

                                $mezua->setSubject($gertakariak[0]->getEgoera().' '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
                                $html='<table border=0><tr><td colspan=2><img src="'.$cid.'" /></td></tr>'
                                .'<tr><th colspan=2><hr><br></th></tr>'
                                .'<tr><th align=left><b>Gertakariaren kodea:</b></th><td>'.$gertakariak[0]->getId().'</td></tr>'
                                .'<tr><th colspan=2 align=left><b>Gertakariaren deskribapena:</b></th></tr><tr><td colspan=2>'
                                .$gertakariak[0]->getDeskribapena().'</td></tr>'
                                .'</table>'
                                .'<br>'
                                .'<p>Zuk zabaldutako gertakari honek ondorengo aldaketa izan du:</p>'
                                .'<table border=0>'
                                .'<tr><th align=left><b>Aldaketa:</b></th><td>"'.$gertakariak[0]->getEgoera().'" egoeran jarri da</td></tr>'
                                .'<tr><th align=left><b>Nork egin du:</b></th><td>'.$this->getLangilea()->getName().'</td></tr>'
                                .'</table>'
                                .'<br><br>'
                                .'<hr><p>EZ ERANTZUN MEZU HONI. Mezu hau automatikoki bidali dizu GERKUD gertakarien kudeaketa aplikazioak zuk horrela konfiguratuta daukazulako. Ez baduzu horrelako mezurik jaso nahi, aldatu konfigurazioa "nire datuak" atalean</p>';
                                $mezua->setBody($html);
                                $mezua->setContentType('text/html');
                                $mailer->send($mezua);
                                break;

                        case 6: //Ixtea
//				echo '<script>alert("ixtea")</script>';
	                        $mezua->setSubject('Itxita '.$gertakariak[0]->getId().': '.$gertakariak[0]->getLaburpena());
                                $mezua->setBody($nork.'-(e)k '.$gertakariak[0]->getId()
                                . ' kodea duen gertakaria amiatutzat eman du');
//                                $mailer->send($mezua);

                                $html='<table border=0><tr><td colspan=2><img src="'.$cid.'" /></td></tr>'
				.'<tr><th colspan=2><hr><br></th></tr>'
				.'<tr><th align=left><b>Gertakariaren kodea:</b></th><td>'.$gertakariak[0]->getId().'</td></tr>'
                                .'<tr><th colspan=2 align=left><b>Gertakariaren deskribapena:</b></th></tr><tr><td colspan=2>'
                                .$gertakariak[0]->getDeskribapena().'</td></tr>'
				.'</table>'
                                .'<br>'
                                .'<p>Zuk zabaldutako gertakari honek ondorengo aldaketa izan du:</p>'
				.'<table border=0>'
                                .'<tr><th align=left><b>Aldaketa:</b></th><td>Itxi'.'</td></tr>'
                                .'<tr><th align=left><b>Nork egin du:</b></th><td>'.$this->getLangilea()->getName().'</td></tr>'
				.'</table>'
				.'<br><br>'
				.'<hr><p>EZ ERANTZUN MEZU HONI. Mezu hau automatikoki bidali dizu GERKUD gertakarien kudeaketa aplikazioak zuk horrela konfiguratuta daukazulako. Ez baduzu horrelako mezurik jaso nahi, aldatu konfigurazioa "nire datuak" atalean</p>';
                                $mezua->setBody($html);
				$mezua->setContentType('text/html');
                                $mailer->send($mezua);
                                break;
			default :
				echo '<script>alert("Ez du mota irakurri")</script>';
			}
                }
	        return $ret;
	}
	catch (Exception $e)
	{
//	        $conn->rollBack();
	        throw $e;
	}
}



}
