<?php

/**
 * Kontaktua
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Kontaktua extends BaseKontaktua
{
	public function __toString()
	{
		if ($this->getIzena() != null && $this->getAbizenak() != null)
			return sprintf('%s %s', $this->getIzena(), $this->getAbizenak());
		else if ($this->getIzena() != null)
			return $this->getIzena();
		else if ($this->getTelefonoa() != null)
			return $this->getTelefonoa();
		else if ($this->getPosta() != null)
			return $this->getPosta();

		return '';
	}

	public function has_data()
	{
		if (is_null($this->getId()))
			return false;

		if (!empty($this->getIzena()))
			return true;

		if (!empty($this->getAbizenak()))
			return true;

		if (!empty($this->getTelefonoa()))
			return true;

		if (!empty($this->getPosta()))
			return true;

		if (!empty($this->getNan()))
			return true;

		return false;
	}
}
