<?php

/**
 * KontaktuaOhartarazteaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KontaktuaOhartarazteaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return KontaktuaOhartarazteaTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KontaktuaOhartaraztea');
    }
}