<?php

/**
 * Mota
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gerkud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Mota extends BaseMota
{
	public function __toString()
	{
		return $this->getIzena();
	}

	/*
	 * Motari dagozkion saileko langileak eskuratu
	 */
	protected function getLangileak()
	{
		$sql = 'SELECT DISTINCT e.user_id AS id'
		 . ' FROM sf_guard_user_group e,'
		 . '  sf_guard_group s,'
		 . '  saila_mota sm,'
		 . '  mota m'
		 . ' WHERE s.id = e.group_id'
		 . '  AND s.id = sm.saila_id'
		 . '  AND m.id = sm.mota_id'
		 . '  AND m.id = :mota';

		$parametroak = array();
		$parametroak[':mota'] = $this->getId();

		$cn = Doctrine_Manager::getInstance()->connection();
		$cmd = $cn->prepare($sql);
		$cmd->execute($parametroak);
		$cursor = $cmd->fetchAll(PDO::FETCH_ASSOC);
		$cmd->closeCursor();

		$erabiltzaileak = array();
		foreach ($cursor as $registro)
		{
			array_push($erabiltzaileak, $registro["id"]);
		}
		return $erabiltzaileak;
	}
}
