<?php

/**
 * Saila
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gerkud
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Saila extends BaseSaila
{
	/*
	 * Saileko langileak eskuratu
	 */
	public function getLangileak()
	{
		$sql = 'SELECT DISTINCT e.user_id AS id'
		 . ' FROM sf_guard_user_group e,'
		 . '  sf_guard_group s'
		 . ' WHERE s.id = e.group_id'
		 . '  AND s.id = :saila';

		$parametroak = array();
		$parametroak[':saila'] = $this->getId();

		$cn = Doctrine_Manager::getInstance()->connection();
		$cmd = $cn->prepare($sql);
		$cmd->execute($parametroak);
		$cursor = $cmd->fetchAll(PDO::FETCH_ASSOC);
		$cmd->closeCursor();

		$erabiltzaileak = array();
		foreach ($cursor as $registro)
		{
			array_push($erabiltzaileak, $registro["id"]);
		}

		return $erabiltzaileak;
	}

	public function __toString()
	{
		// Fix PHP 7
		if ($this->getTable()->hasRelation('Translation'))
			$this->loadReference('Translation');

		if (!is_null($this->getId()))
			return $this->getName();
		else
			return '';
	}
}
