<?php

/**
 * BasesfGuardUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                    $user_id                              Type: integer, primary key
 * @property int                    $permission_id                        Type: integer, primary key
 * @property sfGuardUser            $User                                 
 * @property sfGuardPermission      $Permission                           
 *  
 * @method int                      getUserId()                           Type: integer, primary key
 * @method int                      getPermissionId()                     Type: integer, primary key
 * @method sfGuardUser              getUser()                             
 * @method sfGuardPermission        getPermission()                       
 *  
 * @method sfGuardUserPermission    setUserId(int $val)                   Type: integer, primary key
 * @method sfGuardUserPermission    setPermissionId(int $val)             Type: integer, primary key
 * @method sfGuardUserPermission    setUser(sfGuardUser $val)             
 * @method sfGuardUserPermission    setPermission(sfGuardPermission $val) 
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_permission');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardPermission as Permission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}