<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                                       $first_name                                        Type: string(255)
 * @property string                                       $last_name                                         Type: string(255)
 * @property string                                       $email_address                                     Type: string(255), unique
 * @property string                                       $username                                          Type: string(128), unique
 * @property string                                       $algorithm                                         Type: string(128), default "sha1"
 * @property string                                       $salt                                              Type: string(128)
 * @property string                                       $password                                          Type: string(128)
 * @property bool                                         $is_active                                         Type: boolean, default "1"
 * @property bool                                         $is_super_admin                                    Type: boolean
 * @property string                                       $last_login                                        Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property int                                          $ohartaraztea_id                                   Type: integer
 * @property Doctrine_Collection|sfGuardGroup[]           $Groups                                            
 * @property Doctrine_Collection|sfGuardPermission[]      $Permissions                                       
 * @property Doctrine_Collection|sfGuardUserPermission[]  $sfGuardUserPermission                             
 * @property Doctrine_Collection|sfGuardUserGroup[]       $sfGuardUserGroup                                  
 * @property sfGuardRememberKey                           $RememberKeys                                      
 * @property sfGuardForgotPassword                        $ForgotPassword                                    
 *  
 * @method string                                         getFirstName()                                     Type: string(255)
 * @method string                                         getLastName()                                      Type: string(255)
 * @method string                                         getEmailAddress()                                  Type: string(255), unique
 * @method string                                         getUsername()                                      Type: string(128), unique
 * @method string                                         getAlgorithm()                                     Type: string(128), default "sha1"
 * @method string                                         getSalt()                                          Type: string(128)
 * @method string                                         getPassword()                                      Type: string(128)
 * @method bool                                           getIsActive()                                      Type: boolean, default "1"
 * @method bool                                           getIsSuperAdmin()                                  Type: boolean
 * @method string                                         getLastLogin()                                     Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method int                                            getOhartarazteaId()                                Type: integer
 * @method Doctrine_Collection|sfGuardGroup[]             getGroups()                                        
 * @method Doctrine_Collection|sfGuardPermission[]        getPermissions()                                   
 * @method Doctrine_Collection|sfGuardUserPermission[]    getSfGuardUserPermission()                         
 * @method Doctrine_Collection|sfGuardUserGroup[]         getSfGuardUserGroup()                              
 * @method sfGuardRememberKey                             getRememberKeys()                                  
 * @method sfGuardForgotPassword                          getForgotPassword()                                
 *  
 * @method sfGuardUser                                    setFirstName(string $val)                          Type: string(255)
 * @method sfGuardUser                                    setLastName(string $val)                           Type: string(255)
 * @method sfGuardUser                                    setEmailAddress(string $val)                       Type: string(255), unique
 * @method sfGuardUser                                    setUsername(string $val)                           Type: string(128), unique
 * @method sfGuardUser                                    setAlgorithm(string $val)                          Type: string(128), default "sha1"
 * @method sfGuardUser                                    setSalt(string $val)                               Type: string(128)
 * @method sfGuardUser                                    setPassword(string $val)                           Type: string(128)
 * @method sfGuardUser                                    setIsActive(bool $val)                             Type: boolean, default "1"
 * @method sfGuardUser                                    setIsSuperAdmin(bool $val)                         Type: boolean
 * @method sfGuardUser                                    setLastLogin(string $val)                          Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method sfGuardUser                                    setOhartarazteaId(int $val)                        Type: integer
 * @method sfGuardUser                                    setGroups(Doctrine_Collection $val)                
 * @method sfGuardUser                                    setPermissions(Doctrine_Collection $val)           
 * @method sfGuardUser                                    setSfGuardUserPermission(Doctrine_Collection $val) 
 * @method sfGuardUser                                    setSfGuardUserGroup(Doctrine_Collection $val)      
 * @method sfGuardUser                                    setRememberKeys(sfGuardRememberKey $val)           
 * @method sfGuardUser                                    setForgotPassword(sfGuardForgotPassword $val)      
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ohartaraztea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardForgotPassword as ForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}