<?php

/**
 * BasesfGuardUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int               $user_id                    Type: integer, primary key
 * @property int               $group_id                   Type: integer, primary key
 * @property sfGuardUser       $User                       
 * @property sfGuardGroup      $Group                      
 *  
 * @method int                 getUserId()                 Type: integer, primary key
 * @method int                 getGroupId()                Type: integer, primary key
 * @method sfGuardUser         getUser()                   
 * @method sfGuardGroup        getGroup()                  
 *  
 * @method sfGuardUserGroup    setUserId(int $val)         Type: integer, primary key
 * @method sfGuardUserGroup    setGroupId(int $val)        Type: integer, primary key
 * @method sfGuardUserGroup    setUser(sfGuardUser $val)   
 * @method sfGuardUserGroup    setGroup(sfGuardGroup $val) 
 *  
 * @package    gerkud
 * @subpackage model
 * @author     Pasaiako Udala
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_group');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}