SET foreign_key_checks = 0;

TRUNCATE TABLE jatorrizko_saila;
INSERT INTO `jatorrizko_saila` (`id`) VALUES
  (1),
  (2),
  (3),
  (4),
  (5),
  (6),
  (7),
  (8),
  (9),
  (10),
  (11),
  (12),
  (13),
  (14),
  (15),
  (16),
  (17),
  (18),
  (19),
  (20);

TRUNCATE TABLE jatorrizko_saila_translation;
INSERT INTO `jatorrizko_saila_translation` (`id`, `izena`, `lang`) VALUES
  (1, 'Área Económica', 'es'),
  (1, 'Arlo-Ekonomikoa', 'eu'),
  (2, 'Alcaldía', 'es'),
  (2, 'Alkatetza', 'eu'),
  (3, 'Juzgado de Paz', 'es'),
  (3, 'Bake Epaitegia', 'eu'),
  (4, 'CIP', 'es'),
  (4, 'CIP', 'eu'),
  (5, 'Registro', 'es'),
  (5, 'Erregistroa', 'eu'),
  (6, 'Euskaltegi', 'es'),
  (6, 'Euskaltegia', 'eu'),
  (7, 'Servicios Sociales', 'es'),
  (7, 'Gizartekintza', 'eu'),
  (8, 'Urbanismo', 'es'),
  (8, 'Hirigntza', 'eu'),
  (9, 'Secretaría', 'es'),
  (9, 'Idazkaritza', 'eu'),
  (10, 'Informática', 'es'),
  (10, 'Informatika', 'eu'),
  (11, 'Cultura', 'es'),
  (11, 'Kultura', 'eu'),
  (12, 'Errenteria Musical', 'es'),
  (12, 'Errenteria Musikal', 'eu'),
  (13, 'Personal', 'es'),
  (13, 'Pertsonala', 'eu'),
  (14, 'Sindicatos', 'es'),
  (14, 'Sindikatuak', 'eu'),
  (15, 'Grupo Político', 'es'),
  (15, 'Talde Politikoa', 'eu'),
  (16, 'Policia municipal', 'es'),
  (16, 'Udaltzaingoa', 'eu'),
  (17, 'Residencia de Ancianos', 'es'),
  (17, 'Zaharren Egoitza', 'eu'),
  (18, 'Servicios', 'es'),
  (18, 'Zerbitzuak', 'eu'),
  (19, 'Otros (externos)', 'es'),
  (19, 'Beste batzuk (kanpokoak)', 'eu'),
  (20, 'Deporte', 'es'),
  (20, 'Kirola', 'eu');

SET foreign_key_checks = 1;
