SET foreign_key_checks = 0;

TRUNCATE TABLE kalea;
INSERT INTO `kalea` (`id`, `barrutia_id`, `izena`, `google`) VALUES
  (1110, 1, 'Donibane kalea', 'Donibane kalea'),
  (1120, 1, 'Bonantzako pasealekua', 'Bonanza Pasealekua'),
  (1130, 1, 'Arrokaundietabidea', 'Arrokaundieta Bidea'),
  (1210, 1, 'Lezobidea', 'Lezo Bidea'),
  (1220, 1, 'Jose Joakin Otaegi plaza', 'Jose Joaquin Otaegi plaza'),
  (1230, 1, 'San Roke kalea', 'San Roke kalea'),
  (1240, 1, 'Juan XXIII kalea', 'Juan XXIII kalea'),
  (1250, 1, 'Bordalaborda kalea', 'Bordalaborda kalea'),
  (1260, 1, 'Meipi kalea', 'Meipi kalea'),
  (1270, 1, 'Lurdestxiki kalea', 'Lourdes Txiki kalea'),
  (2110, 2, 'San Pedro kalea', 'San Pedro kalea'),
  (2111, 2, 'Arraunlari kalea', 'Arraunlari kalea'),
  (2120, 2, 'Torreatze kalea', 'Torreatze kalea'),
  (2130, 2, 'Ondartxoko pasealekua', 'Ondartxo pasealekua'),
  (2140, 2, 'Herriko plaza', 'Herriko plaza'),
  (2150, 2, 'Passaman Alargunaren kalea', 'Pasaman Alargunaren kalea'),
  (2170, 2, 'Errekako plaza', 'Errekako plaza'),
  (2180, 2, 'Morales Oliver plaza', 'Morales Oliver plaza'),
  (2190, 2, 'Seoane Markesaren plaza', 'Seoane Markesaren plaza'),
  (2191, 2, 'Frontoiko zumardia', 'Frontoiko zumardia'),
  (2192, 2, 'Markina Ingeniariaren kalea', 'Markina Ingeniariaren kalea'),
  (2210, 2, 'Esnabide kalea', 'Esnabide kalea'),
  (2220, 2, 'Espinosa de los Monteros kalea', 'Espinosa de los Monteros kalea'),
  (2230, 2, 'Ricardo Arrillaga kalea', 'Ricardo Arrillaga kalea'),
  (2240, 2, 'Daniel de Castelao kalea', 'Daniel de Castelao kalea'),
  (2250, 2, 'Urrestarazu Anaien kalea', 'Urrestarazu Anaien kalea'),
  (2260, 2, 'Salinas kalea', 'Salinas kalea'),
  (2270, 4, 'Marinel kalea', 'Marinel kalea'),
  (2280, 2, 'Farolako bidea', 'Faro pasealekua'),
  (2310, 2, 'Kanpitxo kalea', 'Kampitxo kalea'),
  (2320, 2, 'Pabloenea kalea', 'Pabloenea bidea'),
  (2330, 4, 'Gran Sol kalea', 'Gran Sol kalea'),
  (2370, 2, 'Bordaenea kalea', 'Bordaenea kalea'),
  (2410, 4, 'Euskadi etorbidea', 'Euskadi etorbidea'),
  (2420, 4, 'Arrandegi kalea', 'Arrandegi kalea'),
  (2421, 4, 'Serafin Esnaola plaza', 'Serafin Esnaola plaza'),
  (2430, 4, 'Araneder kalea', 'Araneder kalea'),
  (2440, 4, 'Terranova kalea', 'Terranova kalea'),
  (2520, 4, 'Herrera kalea', 'Herrera kalea'),
  (2530, 5, 'Aduana kalea', 'Aduana kalea'),
  (2540, 5, 'Kontsignatario kalea', 'Consignatario kalea'),
  (2610, 4, 'Jaizkibel kalea', 'Jaizkibel kalea'),
  (2620, 4, 'Karmengo Ama plaza', 'Karmengo Ama plaza'),
  (2630, 4, 'Andonaegi kalea', 'Andonaegi kalea'),
  (2640, 4, 'Urgull kalea', 'Urgull kalea'),
  (2650, 4, 'Donostia kalea', 'Donostia kalea'),
  (2710, 4, 'Azkuene kalea', 'Azkuene kalea'),
  (2720, 4, 'Ulia etorbidea', 'Ulia etorbidea'),
  (2730, 4, 'Martimuno kalea', 'Martimuno kalea'),
  (2740, 4, 'Tokialai kalea', 'Tokialai kalea'),
  (2750, 4, 'Oiartzun kalea', 'Oiartzun kalea'),
  (2760, 4, 'Igeldo kalea', 'Igeldo kalea'),
  (2770, 4, 'Mendiolabidea', 'Mendiola bidea'),
  (2780, 4, 'Bidasoa kalea', 'Bidasoa kalea'),
  (2820, 4, 'Errenteria kalea', 'Errenderia kalea'),
  (3110, 3, 'Nafarroa etorbidea', 'Carretera Madrid-Irún'),
  (3120, 3, 'Blas de Lezo kalea', 'Blas de Lezo kalea'),
  (3130, 3, 'Eskalantegi kalea', 'Eskalantegi kalea'),
  (3140, 3, 'Maiatzaren Lehena kalea', 'Maiaizaren Lehena kalea'),
  (3150, 3, 'Zumalakarregi kalea', 'Zumalakarregi kalea'),
  (3160, 3, 'Gure Zumardia', 'Gure Zumardia'),
  (3220, 3, 'Sanmarkobidea', 'San Markos Errepidea'),
  (3230, 3, 'Gelasio Aranburu kalea', 'Gelasio Aranburu kalea'),
  (3240, 3, 'Manuel Azurmendi kalea', 'Manuel Azurmendi kalea'),
  (3250, 3, 'Hamarretxeta kalea', 'Hamarretxeta kalea'),
  (3290, 3, 'Biteri plaza', 'Biteri plaza'),
  (3330, 3, 'Oarso kalea', 'Oarso kalea'),
  (3340, 3, 'Kupeldegi kalea', 'Kupeldegi kalea'),
  (3350, 3, 'Axular plaza', 'Axular plaza'),
  (6001, 1, 'Santiago plaza', 'Donibane kalea 118'),
  (6002, 1, 'Larrabideko bidea', 'Larrabide bidea'),
  (6003, 1, 'Jaizkibelbidea', 'GI-3440'),
  (6004, 1, 'Donibaneko pasealekua', 'Donibane kalea'),
  (6005, 2, 'Torreko plaza', 'Torreko plaza'),
  (6007, 4, 'GUDARIEN PLAZA', 'Gudarien enp.'),
  (6009, 4, 'PASEO DE LOS CURAS', 'Karmengo Ama plaza'),
  (6010, 1, 'BIZKAIA PLAZA', 'BIZKAIA PLAZA'),
  (6011, 4, 'GERNIKA PLAZA', 'GERNIKA PLAZA'),
  (6013, 1, 'Nabalaldea', 'Poligono navalaldea'),
  (6014, 1, 'JUANDANBURU PARKEA', 'JUANDANBURU PARKEA'),
  (6015, 3, 'USOZ PLAZA', 'USOZ PLAZA');

SET foreign_key_checks = 1;
